// ═══════════════════════════════════════════════════════════════════════════
// GERADO por scripts/build-atividades.mjs a partir de
// scripts/atividades.manifest.json. Não editar à mão: rode
//   node scripts/build-atividades.mjs
//
// É o acervo que a Home mostra quando o banco volta vazio. Os uuids são os
// mesmos da migration 012, então favoritar no fallback e no banco dá no
// mesmo registro.
// ═══════════════════════════════════════════════════════════════════════════

import type { Resource } from "./types";

export const atividades: Resource[] = [
  {
    id: "a01a7eca-0002-4000-8000-000000000001",
    title: "1º Ano — Gramática: Monte a Palavra",
    description: "Três jogos de recortar e colar: montar palavras a partir de sílabas, caçar as vogais que faltam e organizar palavras soltas em frases. Trabalha consciência fonológica e formação de frases.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/1o-ano-gramatica-monte-a-palavra/1o-ano-gramatica-monte-a-palavra.pdf",
    imageUrl: "/atividades/ludica/1o-ano-gramatica-monte-a-palavra/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000002",
    title: "1º Ano — Redação: Histórias Incríveis",
    description: "Sorteia personagem, lugar e objeto recortados para inventar uma história maluca, ordena as cenas de uma narrativa e monta a própria história em quatro quadros com desenho e escrita.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/1o-ano-redacao-historias-incriveis/1o-ano-redacao-historias-incriveis.pdf",
    imageUrl: "/atividades/ludica/1o-ano-redacao-historias-incriveis/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000003",
    title: "1º Ano — Interpretação: Detetive da História",
    description: "Lê um texto curto e cola as respostas de quem, onde e o quê; liga cada personagem à sua ação e recorta três cenas para colocar na ordem certa.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/1o-ano-interpretacao-detetive-da-historia/1o-ano-interpretacao-detetive-da-historia.pdf",
    imageUrl: "/atividades/ludica/1o-ano-interpretacao-detetive-da-historia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000004",
    title: "2º Ano — Gramática: A Casa dos Substantivos",
    description: "Classifica doze palavras em pessoas, animais, objetos e lugares, identifica o verbo que indica a ação em cada frase e combina adjetivos com os substantivos certos.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/2o-ano-gramatica-casa-dos-substantivos/2o-ano-gramatica-casa-dos-substantivos.pdf",
    imageUrl: "/atividades/ludica/2o-ano-gramatica-casa-dos-substantivos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000005",
    title: "2º Ano — Redação: Fábrica de Histórias",
    description: "Combina personagem, lugar e acontecimento recortados, ordena cartas para montar o enredo e reescreve o final de uma história dada. Trabalha estrutura narrativa e criatividade.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/2o-ano-redacao-fabrica-de-historias/2o-ano-redacao-fabrica-de-historias.pdf",
    imageUrl: "/atividades/ludica/2o-ano-redacao-fabrica-de-historias/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000006",
    title: "2º Ano — Interpretação: Mapa da História",
    description: "Responde a perguntas de quem, onde e quando sobre um texto curto, desembaralha as cenas de uma narrativa e preenche o mapa da história com personagens, lugar, problema e desfecho.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/2o-ano-interpretacao-mapa-da-historia/2o-ano-interpretacao-mapa-da-historia.pdf",
    imageUrl: "/atividades/ludica/2o-ano-interpretacao-mapa-da-historia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000007",
    title: "3º Ano — Gramática: Detetives da Pontuação",
    description: "Recorta os sinais de pontuação e cola nos lugares certos de um texto sem pontuação, reescreve o texto pontuado e completa frases com o sinal que falta.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/3o-ano-gramatica-detetives-da-pontuacao/3o-ano-gramatica-detetives-da-pontuacao.pdf",
    imageUrl: "/atividades/ludica/3o-ano-gramatica-detetives-da-pontuacao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000008",
    title: "3º Ano — Redação: Meu Primeiro Jornal",
    description: "Cria um personagem em ficha e desenho, dá continuidade a uma história começada e escreve uma notícia seguindo a estrutura de título, quem, onde, quando, o quê, por quê e como.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/3o-ano-redacao-meu-primeiro-jornal/3o-ano-redacao-meu-primeiro-jornal.pdf",
    imageUrl: "/atividades/ludica/3o-ano-redacao-meu-primeiro-jornal/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000009",
    title: "3º Ano — Interpretação: O Cachorro Fiel",
    description: "Lê o texto sobre o cachorro fiel e responde cinco perguntas, marca verdadeiro ou falso, preenche o mapa da história com problema e lição e separa palavras em sílabas.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/3o-ano-interpretacao-o-cachorro-fiel/3o-ano-interpretacao-o-cachorro-fiel.pdf",
    imageUrl: "/atividades/ludica/3o-ano-interpretacao-o-cachorro-fiel/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000010",
    title: "4º Ano — Gramática: As Palavras Têm Poder",
    description: "Seis blocos de gramática numa folha só: classes de palavras, substantivos comuns e próprios, tempos verbais, sinais de pontuação, caça ao erro e formação de frases.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/4o-ano-gramatica-as-palavras-tem-poder/4o-ano-gramatica-as-palavras-tem-poder.pdf",
    imageUrl: "/atividades/ludica/4o-ano-gramatica-as-palavras-tem-poder/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000011",
    title: "4º Ano — Redação: Crie seu Personagem",
    description: "Preenche a ficha completa de um personagem, escreve uma história com começo, meio e fim e produz uma página de diário. Inclui tabela de revisão da própria produção.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/4o-ano-redacao-crie-seu-personagem/4o-ano-redacao-crie-seu-personagem.pdf",
    imageUrl: "/atividades/ludica/4o-ano-redacao-crie-seu-personagem/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000012",
    title: "4º Ano — Interpretação: A Importância das Abelhas",
    description: "Sete blocos sobre um texto informativo: perguntas de compreensão, verdadeiro ou falso, antônimos, inferência, ordem dos fatos, ligação de ideias e produção de opinião.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/4o-ano-interpretacao-a-importancia-das-abelhas/4o-ano-interpretacao-a-importancia-das-abelhas.pdf",
    imageUrl: "/atividades/ludica/4o-ano-interpretacao-a-importancia-das-abelhas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000013",
    title: "5º Ano — Gramática: Classes e Concordância",
    description: "Classes de palavras, substantivos concretos e abstratos, figuras de linguagem, sujeito e predicado, tempos e modos verbais e correção de erros de concordância.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/5o-ano-gramatica-classes-e-concordancia/5o-ano-gramatica-classes-e-concordancia.pdf",
    imageUrl: "/atividades/ludica/5o-ano-gramatica-classes-e-concordancia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000014",
    title: "5º Ano — Redação: Planeje sua História",
    description: "Cria o personagem, planeja a história em começo, meio e fim antes de escrever e produz o texto final. Fecha com uma tabela de autoavaliação da produção.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/5o-ano-redacao-planeje-sua-historia/5o-ano-redacao-planeje-sua-historia.pdf",
    imageUrl: "/atividades/ludica/5o-ano-redacao-planeje-sua-historia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000015",
    title: "5º Ano — Interpretação: A Importância da Leitura",
    description: "Oito blocos sobre um texto argumentativo: compreensão, verdadeiro ou falso, inferências, antônimos, ordem dos fatos, palavras no contexto e produção de opinião.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/5o-ano-interpretacao-a-importancia-da-leitura/5o-ano-interpretacao-a-importancia-da-leitura.pdf",
    imageUrl: "/atividades/ludica/5o-ano-interpretacao-a-importancia-da-leitura/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000016",
    title: "Caça ao Tesouro das Palavras",
    description: "Seis pistas descrevem objetos do dia a dia. A criança recorta as palavras e cola cada tesouro no lugar certo do mapa pirata. Trabalha leitura, vocabulário e associação.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-ao-tesouro-das-palavras/caca-ao-tesouro-das-palavras.pdf",
    imageUrl: "/atividades/ludica/caca-ao-tesouro-das-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000017",
    title: "Bingo das Palavras",
    description: "Cartela de dezesseis palavras com imagem e dez pistas para o professor ler em voz alta. Inclui fichas recortáveis para marcar e um desafio de criar frases com três palavras sorteadas.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/bingo-das-palavras/bingo-das-palavras.pdf",
    imageUrl: "/atividades/ludica/bingo-das-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000018",
    title: "Memória de Palavras e Imagens",
    description: "Vinte cartas para recortar formam dez pares de palavra e imagem. Depois do jogo da memória, a criança escolhe três pares e escreve uma frase ou história curta.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/memoria-de-palavras-e-imagens/memoria-de-palavras-e-imagens.pdf",
    imageUrl: "/atividades/ludica/memoria-de-palavras-e-imagens/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000019",
    title: "Dominó de Palavras",
    description: "Peças de imagem, palavra e definição para recortar e encaixar como um dominó, com tabuleiro em branco para montar as combinações. Trabalha leitura e significado.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/domino-de-palavras/domino-de-palavras.pdf",
    imageUrl: "/atividades/ludica/domino-de-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000020",
    title: "Roleta da Imaginação",
    description: "Roleta de quatro quadrantes — personagem, lugar, objeto e ação — montada com colchete. A criança gira, registra o sorteio na ficha e escreve a história que saiu.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/roleta-da-imaginacao/roleta-da-imaginacao.pdf",
    imageUrl: "/atividades/ludica/roleta-da-imaginacao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000021",
    title: "Quebra-Cabeça da História",
    description: "Quatro cenas de uma história para recortar, organizar na ordem que faz sentido e colar. Depois a criança reconta a narrativa com as próprias palavras.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/quebra-cabeca-da-historia/quebra-cabeca-da-historia.pdf",
    imageUrl: "/atividades/ludica/quebra-cabeca-da-historia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000022",
    title: "Quem Sou Eu?",
    description: "Quatro conjuntos de pistas descrevem um objeto ou animal. A criança recorta as oito cartas e cola a resposta certa em cada quadro, depois cria uma frase com ela.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/quem-sou-eu/quem-sou-eu.pdf",
    imageUrl: "/atividades/ludica/quem-sou-eu/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000023",
    title: "Complete o Desenho e Conte",
    description: "Quatro cenas incompletas para a criança terminar de desenhar, com um banco de dez ideias ilustradas. Em seguida escreve uma frase, legenda ou história curta sobre o que criou.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/complete-o-desenho-e-conte/complete-o-desenho-e-conte.pdf",
    imageUrl: "/atividades/ludica/complete-o-desenho-e-conte/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000024",
    title: "Trilha das Palavras",
    description: "Tabuleiro de dezenove casas com desafios de leitura, fala e criatividade, com peões e dado para recortar e montar. Pode ser jogado em dupla, em grupo ou sozinho.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/trilha-das-palavras/trilha-das-palavras.pdf",
    imageUrl: "/atividades/ludica/trilha-das-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000025",
    title: "Desafio das Rimas",
    description: "Cinco pares que rimam para ligar e dez cartas para recortar e juntar. Fecha com a escrita de uma frase e de um versinho usando o par favorito.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/desafio-das-rimas/desafio-das-rimas.pdf",
    imageUrl: "/atividades/ludica/desafio-das-rimas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000026",
    title: "Monstro das Emoções",
    description: "Monta um monstrinho com cabeça, olhos, boca, braços, pernas e acessórios recortáveis, escolhe entre seis emoções e escreve como ele está se sentindo e por quê.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/monstro-das-emocoes/monstro-das-emocoes.pdf",
    imageUrl: "/atividades/ludica/monstro-das-emocoes/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000027",
    title: "Monstro das Emoções — Monte e Conte",
    description: "Versão ampliada: monta o monstro com as peças recortáveis, escolhe a emoção numa escala de seis e responde por que ele se sente assim, o que aconteceu e o que pode melhorar.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/monstro-das-emocoes-monte-e-conte/monstro-das-emocoes-monte-e-conte.pdf",
    imageUrl: "/atividades/ludica/monstro-das-emocoes-monte-e-conte/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000028",
    title: "Missão dos Piratas",
    description: "Seis pistas indicam o caminho até o tesouro escondido. A criança recorta navio, caverna, vulcão, ponte e baú, monta o mapa na ordem certa e responde ao desafio extra.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/missao-dos-piratas/missao-dos-piratas.pdf",
    imageUrl: "/atividades/ludica/missao-dos-piratas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000029",
    title: "Parque dos Dinossauros",
    description: "Nove dinossauros para recortar e colar no habitat correto — floresta, vulcão, lago, deserto ou caverna — com cards explicativos, três perguntas e o desafio de criar um dino inédito.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/parque-dos-dinossauros/parque-dos-dinossauros.pdf",
    imageUrl: "/atividades/ludica/parque-dos-dinossauros/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000030",
    title: "Laboratório do Cientista",
    description: "Combina tubos de ensaio, ingredientes e equipamentos recortáveis em três experimentos, preenche a ficha da invenção e desenha o resultado. Inclui cartas-surpresa que mudam tudo.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/laboratorio-do-cientista/laboratorio-do-cientista.pdf",
    imageUrl: "/atividades/ludica/laboratorio-do-cientista/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000031",
    title: "Fábrica de Super-Heróis",
    description: "Monta o herói com máscara, capa, uniforme, acessórios e símbolo recortáveis, escolhe os superpoderes, preenche a ficha e escreve uma aventura cumprindo as missões do dia.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/fabrica-de-super-herois/fabrica-de-super-herois.pdf",
    imageUrl: "/atividades/ludica/fabrica-de-super-herois/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000032",
    title: "Construa um Castelo",
    description: "Torres, muralhas, portões, bandeiras, decorações e personagens para recortar e montar o castelo. Depois a criança descreve quem mora nele, desenha o interior e cria o brasão.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/construa-um-castelo/construa-um-castelo.pdf",
    imageUrl: "/atividades/ludica/construa-um-castelo/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000033",
    title: "Safari dos Animais",
    description: "Dez animais para recortar e colar no habitat certo — savana, floresta, oceano, deserto e polo norte —, três perguntas de observação, jogo da memória e um animal inventado.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/safari-dos-animais/safari-dos-animais.pdf",
    imageUrl: "/atividades/ludica/safari-dos-animais/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000034",
    title: "Mercado Divertido",
    description: "Monta a cesta seguindo três listas de compras, recorta produtos por setor — hortifruti, laticínios, padaria, higiene e bebidas — e trabalha etiquetas de preço com cartas-surpresa.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/mercado-divertido/mercado-divertido.pdf",
    imageUrl: "/atividades/ludica/mercado-divertido/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000035",
    title: "Restaurante Maluco",
    description: "Três clientes fazem pedidos e a criança monta cada prato com ingredientes recortáveis, escreve o menu do dia e encara o desafio do chef com as cartas-surpresa.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/restaurante-maluco/restaurante-maluco.pdf",
    imageUrl: "/atividades/ludica/restaurante-maluco/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000036",
    title: "Missão dos Bombeiros",
    description: "Monta a cena de resgate com veículos, equipamentos e personagens recortáveis, numera o plano de resgate na ordem correta e escreve o que aconteceu. Ensina quando ligar 193.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/missao-dos-bombeiros/missao-dos-bombeiros.pdf",
    imageUrl: "/atividades/ludica/missao-dos-bombeiros/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000037",
    title: "Escola de Magia",
    description: "Cria o próprio mago escolhendo chapéu, varinha, livro e cristal, inventa três poções e um feitiço, joga a memória mágica e escreve a aventura na escola de magia.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/escola-de-magia/escola-de-magia.pdf",
    imageUrl: "/atividades/ludica/escola-de-magia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000038",
    title: "Navio Fantasma",
    description: "Mistério de detetive a bordo: monta a cena com as peças recortáveis, resolve o enigma do código e preenche o diário do pirata contando o que descobriu.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/navio-fantasma/navio-fantasma.pdf",
    imageUrl: "/atividades/ludica/navio-fantasma/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000039",
    title: "Acampamento na Floresta",
    description: "Monta o acampamento, escolhe seis itens essenciais para a mochila do explorador e registra a aventura no diário. Inclui cartas-surpresa e jogo da memória.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/acampamento-na-floresta/acampamento-na-floresta.pdf",
    imageUrl: "/atividades/ludica/acampamento-na-floresta/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000040",
    title: "Resgate no Fundo do Mar",
    description: "Monta o cenário marinho, separa o que protege do que polui o mar, numera o plano de resgate e resolve o enigma do tesouro. Trabalha consciência ambiental.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/resgate-no-fundo-do-mar/resgate-no-fundo-do-mar.pdf",
    imageUrl: "/atividades/ludica/resgate-no-fundo-do-mar/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000041",
    title: "Óculos do Detetive",
    description: "Recorta os óculos de lentes vermelha e azul, levanta três abas de pistas em camadas e descobre quem pegou o livro mágico da biblioteca. Trabalha inferência e dedução.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/oculos-do-detetive/oculos-do-detetive.pdf",
    imageUrl: "/atividades/ludica/oculos-do-detetive/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000042",
    title: "Máquina das Escolhas",
    description: "Três roletas presas com clipe sorteiam personagem, lugar e missão. A criança gira, combina os elementos e escreve a aventura que saiu no sorteio.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/maquina-das-escolhas/maquina-das-escolhas.pdf",
    imageUrl: "/atividades/ludica/maquina-das-escolhas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000043",
    title: "Cidade Pop-Up",
    description: "Seis prédios dobráveis, personagens e veículos para recortar e montar uma cidade em três dimensões sobre a base. Depois a criança cria histórias que acontecem nela.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/cidade-pop-up/cidade-pop-up.pdf",
    imageUrl: "/atividades/ludica/cidade-pop-up/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000044",
    title: "Trilha da Ilha do Tesouro",
    description: "Jogo de tabuleiro completo para montar: dado de dobrar, marcadores em base de barco, cartas de aventura e envelope do tesouro. Trabalha leitura de instruções e jogo em grupo.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/trilha-da-ilha-do-tesouro/trilha-da-ilha-do-tesouro.pdf",
    imageUrl: "/atividades/ludica/trilha-da-ilha-do-tesouro/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000045",
    title: "Hospital das Frases",
    description: "Cinco frases doentes para diagnosticar: falta de maiúscula, acentuação, pontuação e concordância. A criança encontra o erro e cola a correção recortada.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/hospital-das-frases/hospital-das-frases.pdf",
    imageUrl: "/atividades/ludica/hospital-das-frases/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000046",
    title: "Guarda-Roupa das Palavras",
    description: "Vinte palavras para recortar e guardar na gaveta certa: substantivo, verbo, adjetivo ou pronome. Fecha com a escrita de quatro frases usando as classes trabalhadas.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/guarda-roupa-das-palavras/guarda-roupa-das-palavras.pdf",
    imageUrl: "/atividades/ludica/guarda-roupa-das-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000047",
    title: "Semáforo da Pontuação",
    description: "Cola o sinal certo em cinco frases e depois reescreve duas delas trocando a pontuação para ver como o sentido muda. Trabalha ponto, vírgula, interrogação e exclamação.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/semaforo-da-pontuacao/semaforo-da-pontuacao.pdf",
    imageUrl: "/atividades/ludica/semaforo-da-pontuacao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000048",
    title: "História por Imagens",
    description: "Quatro cenas para recortar e ordenar em começo, meio e fim. Com a sequência montada, a criança escreve a narrativa completa em quatro parágrafos.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/historia-por-imagens/historia-por-imagens.pdf",
    imageUrl: "/atividades/ludica/historia-por-imagens/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000049",
    title: "Diário de um Personagem",
    description: "Escolhe um entre quatro personagens, cola a figura e escreve uma página de diário em primeira pessoa. Inclui autoavaliação da produção escrita.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/diario-de-um-personagem/diario-de-um-personagem.pdf",
    imageUrl: "/atividades/ludica/diario-de-um-personagem/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000050",
    title: "Correio das Frases",
    description: "Oito frases para recortar e entregar no envelope certo: pergunta, ordem, exclamação ou afirmação. Depois a criança escreve uma frase de cada tipo.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/correio-das-frases/correio-das-frases.pdf",
    imageUrl: "/atividades/ludica/correio-das-frases/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000051",
    title: "Fábrica de Personagens",
    description: "Escolhe aparência, personalidade, sonho, medo e objetivo, monta a ficha do personagem e escreve um texto apresentando-o. Base para qualquer produção narrativa.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/fabrica-de-personagens/fabrica-de-personagens.pdf",
    imageUrl: "/atividades/ludica/fabrica-de-personagens/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000052",
    title: "Quebra-Cabeça dos Parágrafos",
    description: "Cinco parágrafos embaralhados para recortar e colar na ordem que forma o texto. A criança cria um título e responde sobre a lição que a história deixa.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/quebra-cabeca-dos-paragrafos/quebra-cabeca-dos-paragrafos.pdf",
    imageUrl: "/atividades/ludica/quebra-cabeca-dos-paragrafos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000053",
    title: "Máquina do Antes e Depois",
    description: "Dez frases ilustradas para recortar e colar na coluna do passado, do presente ou do futuro. Fecha reescrevendo duas delas nos três tempos verbais.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/maquina-do-antes-e-depois/maquina-do-antes-e-depois.pdf",
    imageUrl: "/atividades/ludica/maquina-do-antes-e-depois/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000054",
    title: "Cartas das Emoções",
    description: "Combina personagem, situação e emoção e escreve o que aconteceu, como se sentiu, por quê e o que ajudaria. Trabalha vocabulário emocional e produção escrita.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/cartas-das-emocoes/cartas-das-emocoes.pdf",
    imageUrl: "/atividades/ludica/cartas-das-emocoes/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000055",
    title: "Detetive dos Erros",
    description: "Cinco frases com erro de ortografia, pontuação ou concordância; a criança recorta a correção certa e cola ao lado. No desafio, reescreve uma delas trocando uma palavra por outra parecida.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/detetive-dos-erros/detetive-dos-erros.pdf",
    imageUrl: "/atividades/ludica/detetive-dos-erros/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000056",
    title: "Jornal das Aventuras",
    description: "Monta uma notícia colando manchete, personagem, local e acontecimento nos campos de quem, onde, quando e o quê, ilustra a matéria e cria uma manchete própria mais chamativa.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/jornal-das-aventuras/jornal-das-aventuras.pdf",
    imageUrl: "/atividades/ludica/jornal-das-aventuras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000057",
    title: "Mapa da História — Aventura na Floresta",
    description: "Cola personagem, lugar, problema, acontecimento e final num mapa de trilha e depois reescreve a história completa com as próprias palavras, fechando com um título criativo.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/mapa-da-historia-aventura-na-floresta/mapa-da-historia-aventura-na-floresta.pdf",
    imageUrl: "/atividades/ludica/mapa-da-historia-aventura-na-floresta/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000058",
    title: "Laboratório das Palavras — Misture as Sílabas",
    description: "Combina sílabas de início, meio e fim para descobrir palavras reais e inventar palavras novas, separando as duas listas. No desafio, escreve uma frase com duas das palavras reais.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/laboratorio-das-palavras-misture-as-silabas/laboratorio-das-palavras-misture-as-silabas.pdf",
    imageUrl: "/atividades/ludica/laboratorio-das-palavras-misture-as-silabas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000059",
    title: "Tribunal dos Personagens — O Vaso Quebrado",
    description: "Diante de um menino que quebrou o vaso e inventou uma desculpa, a criança recorta argumentos a favor e contra, monta os dois lados e escreve sua conclusão e um conselho.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/tribunal-dos-personagens-o-vaso-quebrado/tribunal-dos-personagens-o-vaso-quebrado.pdf",
    imageUrl: "/atividades/ludica/tribunal-dos-personagens-o-vaso-quebrado/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000060",
    title: "Varal das Frases — Sujeito, Verbo e Complemento",
    description: "Recorta palavras soltas, monta três frases corretas no varal e depois separa cada uma em sujeito, verbo e complemento numa tabela. Fecha criando uma frase nova.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/varal-das-frases-sujeito-verbo-complemento/varal-das-frases-sujeito-verbo-complemento.pdf",
    imageUrl: "/atividades/ludica/varal-das-frases-sujeito-verbo-complemento/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000061",
    title: "Restaurante dos Adjetivos",
    description: "Escolhe entre dez adjetivos os que melhor descrevem cachorro, casa e menina e cola em cada prato. Depois escreve uma frase com um substantivo e dois adjetivos.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/restaurante-dos-adjetivos/restaurante-dos-adjetivos.pdf",
    imageUrl: "/atividades/ludica/restaurante-dos-adjetivos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000062",
    title: "Elevador das Sílabas",
    description: "Monta palavras com dezoito cartões de sílabas e leva cada uma ao andar certo do elevador: duas, três ou quatro sílabas. Registra uma palavra de cada andar.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/elevador-das-silabas/elevador-das-silabas.pdf",
    imageUrl: "/atividades/ludica/elevador-das-silabas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000063",
    title: "Conserto de Histórias",
    description: "Três historinhas têm um trecho que não faz sentido — peixe voando, casaco de lã na praia. A criança recorta a peça certa e troca, e depois inventa a própria correção.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/conserto-de-historias/conserto-de-historias.pdf",
    imageUrl: "/atividades/ludica/conserto-de-historias/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000064",
    title: "Passaporte das Palavras",
    description: "Doze palavras viajam para o país certo: substantivo, verbo, adjetivo, pronome ou advérbio. Depois a criança carimba o passaporte escrevendo uma frase que usa uma de cada.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/passaporte-das-palavras/passaporte-das-palavras.pdf",
    imageUrl: "/atividades/ludica/passaporte-das-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000065",
    title: "Quadrinhos Embaralhados",
    description: "Quatro cenas de um menino que alimenta um cachorro de rua vêm fora de ordem: recorta, organiza, completa o último balão de fala e escreve o final da história.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/quadrinhos-embaralhados/quadrinhos-embaralhados.pdf",
    imageUrl: "/atividades/ludica/quadrinhos-embaralhados/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000066",
    title: "Sorveteria das Rimas",
    description: "Para cada casquinha — coração, bola, gato — escolhe as bolas de sorvete que rimam. Depois cria um versinho curto usando pelo menos uma das rimas.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/sorveteria-das-rimas/sorveteria-das-rimas.pdf",
    imageUrl: "/atividades/ludica/sorveteria-das-rimas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000067",
    title: "Detetive do Sujeito — Cartões de Investigação",
    description: "Quatro frases sem sujeito e quatro suspeitos para recortar e colar: quem latiu, quem estudou, quem decolou, quem explicou. Fecha inventando uma frase nova.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/detetive-do-sujeito-cartoes-de-investigacao/detetive-do-sujeito-cartoes-de-investigacao.pdf",
    imageUrl: "/atividades/ludica/detetive-do-sujeito-cartoes-de-investigacao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000068",
    title: "Correio do Futuro",
    description: "Escolhe uma situação e um destinatário — você mesmo no futuro, um amigo, a família — e escreve uma carta completa, com começo, mensagem e despedida, num modelo de aerograma.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/correio-do-futuro/correio-do-futuro.pdf",
    imageUrl: "/atividades/ludica/correio-do-futuro/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000069",
    title: "Semáforo da História",
    description: "Organiza a história em começo, problema e final usando as três luzes do semáforo, escolhe cartões de personagem, lugar, problema e solução e escreve o texto completo ao lado.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/semaforo-da-historia/semaforo-da-historia.pdf",
    imageUrl: "/atividades/ludica/semaforo-da-historia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000070",
    title: "Caixa dos Começos",
    description: "Escolhe um começo clássico — Era uma vez, De repente — e recorta cartas de personagem, lugar, objeto e problema para inspirar uma história inédita, com título e cena desenhada.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caixa-dos-comecos/caixa-dos-comecos.pdf",
    imageUrl: "/atividades/ludica/caixa-dos-comecos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000071",
    title: "Máquina do Singular e Plural",
    description: "Cola seis palavras no singular na entrada da máquina e o plural correspondente na saída. Depois escreve uma frase com uma das palavras no plural.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/maquina-do-singular-e-plural/maquina-do-singular-e-plural.pdf",
    imageUrl: "/atividades/ludica/maquina-do-singular-e-plural/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000072",
    title: "Detetive da Pontuação — Cinco Pistas",
    description: "Cinco frases sem pontuação viram pistas: a criança recorta os sinais e descobre qual completa cada uma, com um quadro de dicas explicando o que cada sinal faz.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/detetive-da-pontuacao-cinco-pistas/detetive-da-pontuacao-cinco-pistas.pdf",
    imageUrl: "/atividades/ludica/detetive-da-pontuacao-cinco-pistas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000073",
    title: "Mapa do Conto",
    description: "Um mapa do tesouro organiza personagem, lugar, problema e solução com cartas para recortar — pirata, ilha misteriosa, dragão bravo — e a criança escreve o resumo do conto que montou.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/mapa-do-conto/mapa-do-conto.pdf",
    imageUrl: "/atividades/ludica/mapa-do-conto/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000074",
    title: "Relógio dos Tempos Verbais",
    description: "Nove frases recortadas vão para o setor certo do relógio: passado, presente ou futuro. Depois a criança escreve uma frase própria em cada tempo.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/relogio-dos-tempos-verbais/relogio-dos-tempos-verbais.pdf",
    imageUrl: "/atividades/ludica/relogio-dos-tempos-verbais/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000075",
    title: "Oficina dos Quadrinhos",
    description: "Monta uma tirinha de quatro quadros com personagens, cenários, balões, emoções e onomatopeias para recortar, dá um título e conta a mesma história em texto corrido.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/oficina-dos-quadrinhos/oficina-dos-quadrinhos.pdf",
    imageUrl: "/atividades/ludica/oficina-dos-quadrinhos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000076",
    title: "Tribunal dos Personagens — O Livro Esquecido",
    description: "Lucas esqueceu de devolver o livro da biblioteca. A criança cola argumentos de defesa e de acusação, escreve o veredito com sua opinião e desenha a cena da história.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/tribunal-dos-personagens-o-livro-esquecido/tribunal-dos-personagens-o-livro-esquecido.pdf",
    imageUrl: "/atividades/ludica/tribunal-dos-personagens-o-livro-esquecido/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000077",
    title: "Laboratório dos Sinônimos",
    description: "Cinco estações com feliz, rápido, bonito, grande e bravo esperam a palavra de significado parecido. A criança cola o sinônimo certo e escreve uma frase com um dos pares.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/laboratorio-dos-sinonimos/laboratorio-dos-sinonimos.pdf",
    imageUrl: "/atividades/ludica/laboratorio-dos-sinonimos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000078",
    title: "Trem da Sequência",
    description: "Quatro cenas mostram uma semente virando flor: recorta, coloca na ordem certa dentro dos vagões e conta a história com as próprias palavras, inventando um vagão a mais.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/trem-da-sequencia/trem-da-sequencia.pdf",
    imageUrl: "/atividades/ludica/trem-da-sequencia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000079",
    title: "Baú das Perguntas",
    description: "Lê um texto curto sobre um passeio no parque e encaixa em cada baú a resposta de quem, onde, quando e o que levou. Fecha criando uma pergunta nova para o texto.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/bau-das-perguntas/bau-das-perguntas.pdf",
    imageUrl: "/atividades/ludica/bau-das-perguntas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000080",
    title: "Jardim dos Substantivos",
    description: "Planta oito palavras no canteiro certo — pessoas, animais, objetos ou lugares — e depois escreve uma frase com a palavra favorita e desenha um substantivo novo para cada grupo.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/jardim-dos-substantivos/jardim-dos-substantivos.pdf",
    imageUrl: "/atividades/ludica/jardim-dos-substantivos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000081",
    title: "Missão dos Conectivos",
    description: "Cinco pares de ideias precisam de uma ponte: mas, porque, e, então ou porém. A criança cola o conectivo que liga melhor cada frase e depois cria uma frase própria.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/missao-dos-conectivos/missao-dos-conectivos.pdf",
    imageUrl: "/atividades/ludica/missao-dos-conectivos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000082",
    title: "Cinema da Redação",
    description: "Escolhe personagem, lugar, problema e final entre dezesseis cartas, escreve o roteiro do filme e ainda cria o título e o cartaz de cinema da própria história.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/cinema-da-redacao/cinema-da-redacao.pdf",
    imageUrl: "/atividades/ludica/cinema-da-redacao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000083",
    title: "Radar dos Antônimos",
    description: "Cinco radares mostram alto, quente, cheio, feliz e dia; a criança encontra e cola o contrário de cada um e escreve uma frase usando um dos pares opostos.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/radar-dos-antonimos/radar-dos-antonimos.pdf",
    imageUrl: "/atividades/ludica/radar-dos-antonimos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000084",
    title: "Oficina das Manchetes",
    description: "Três notícias ilustradas — o cachorro que salvou a bola, a horta da escola, a feira de ciências — e seis manchetes para escolher a que combina. Depois escreve como repórter por um dia.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/oficina-das-manchetes/oficina-das-manchetes.pdf",
    imageUrl: "/atividades/ludica/oficina-das-manchetes/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000085",
    title: "Roda dos Pronomes",
    description: "Quatro rodas — eu, você, ele/ela, nós — esperam o pronome certo para completar cada frase, com dois cartões intrusos que não são pronomes. Fecha com uma frase própria.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/roda-dos-pronomes/roda-dos-pronomes.pdf",
    imageUrl: "/atividades/ludica/roda-dos-pronomes/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000086",
    title: "Mercado dos Verbos",
    description: "Cinco bancas do mercado mostram alguém correndo, lendo, dormindo, escrevendo e cantando; a criança cola o verbo certo em cada uma e descarta os dois cartões que não são verbos.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/mercado-dos-verbos/mercado-dos-verbos.pdf",
    imageUrl: "/atividades/ludica/mercado-dos-verbos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000087",
    title: "Detetive do Sujeito — Quem Praticou a Ação?",
    description: "Seis frases sem sujeito e dez suspeitos para recortar: o menino, a professora, os amigos, o gato. No desafio, reescreve duas frases trocando o sujeito por outro que também faça sentido.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/detetive-do-sujeito-quem-praticou-a-acao/detetive-do-sujeito-quem-praticou-a-acao.pdf",
    imageUrl: "/atividades/ludica/detetive-do-sujeito-quem-praticou-a-acao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000088",
    title: "A História em Ordem",
    description: "Quatro cenas da adoção de um cachorrinho num abrigo vêm embaralhadas: a criança organiza, escreve a história completa, cria um título e responde o que aprendeu com ela.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/a-historia-em-ordem/a-historia-em-ordem.pdf",
    imageUrl: "/atividades/ludica/a-historia-em-ordem/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000089",
    title: "Caça-Palavras Temático — Natureza",
    description: "Onze palavras da natureza escondidas na grade, mais perguntas sobre quantas foram achadas e qual é a maior e a menor. Fecha com um pequeno texto sobre a natureza.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-palavras-tematico-natureza/caca-palavras-tematico-natureza.pdf",
    imageUrl: "/atividades/ludica/caca-palavras-tematico-natureza/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000090",
    title: "Caça ao Tesouro das Palavras — A Aventura no Bosque",
    description: "Lê o conto de Lucas no bosque, responde quatro perguntas de interpretação, garimpa substantivos, adjetivos e verbos no texto e escreve o que gostaria de achar numa caixa misteriosa.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-ao-tesouro-das-palavras-a-aventura-no-bosque/caca-ao-tesouro-das-palavras-a-aventura-no-bosque.pdf",
    imageUrl: "/atividades/ludica/caca-ao-tesouro-das-palavras-a-aventura-no-bosque/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000091",
    title: "Caça aos Sinônimos e Antônimos",
    description: "Cinco palavras, duas colunas: a criança cola o sinônimo e o antônimo de cada uma e escreve frases mostrando que entendeu a diferença entre significado parecido e oposto.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-aos-sinonimos-e-antonimos/caca-aos-sinonimos-e-antonimos.pdf",
    imageUrl: "/atividades/ludica/caca-aos-sinonimos-e-antonimos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000092",
    title: "Missão Leitor Detetive",
    description: "Sobre o texto O cachorro e a chuva: cinco perguntas de interpretação, verdadeiro ou falso, caça a palavras com significado dado, completar frases e uma produção de texto ao final.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/missao-leitor-detetive/missao-leitor-detetive.pdf",
    imageUrl: "/atividades/ludica/missao-leitor-detetive/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000093",
    title: "Leitura em Ação — O Dia em Que Tudo Mudou",
    description: "Lê a história do filhote que chegou numa caixa, responde seis perguntas incluindo a mensagem principal, ordena quatro cenas e escreve um novo final.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/leitura-em-acao-o-dia-em-que-tudo-mudou/leitura-em-acao-o-dia-em-que-tudo-mudou.pdf",
    imageUrl: "/atividades/ludica/leitura-em-acao-o-dia-em-que-tudo-mudou/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000094",
    title: "Detetive das Palavras — Substantivos na Cena",
    description: "Observa uma cena de quintal e classifica dez substantivos em pessoas, animais, lugares, objetos e sentimentos. Depois escreve três frases usando as palavras da cena.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/detetive-das-palavras-substantivos-na-cena/detetive-das-palavras-substantivos-na-cena.pdf",
    imageUrl: "/atividades/ludica/detetive-das-palavras-substantivos-na-cena/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000095",
    title: "História em Construção — O Dia Especial",
    description: "Um texto lacunado sobre um passeio de domingo, com banco de nove palavras para recortar e colar. Depois a criança dá outro título, desenha e reescreve a história completa.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/historia-em-construcao-o-dia-especial/historia-em-construcao-o-dia-especial.pdf",
    imageUrl: "/atividades/ludica/historia-em-construcao-o-dia-especial/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000096",
    title: "Laboratório das Palavras — Oficina Completa",
    description: "Seis desafios numa folha só: classificar palavras em quatro classes, formar palavras com sílabas, completar frases, reorganizar frases embaralhadas, criar frases a partir de imagens e montar frases com cartões.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/laboratorio-das-palavras-oficina-completa/laboratorio-das-palavras-oficina-completa.pdf",
    imageUrl: "/atividades/ludica/laboratorio-das-palavras-oficina-completa/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000097",
    title: "Jornal Maluco",
    description: "Monta a capa de um jornal escolhendo manchete, imagem e fonte entre as opções recortáveis, e depois escreve a própria notícia respondendo o quê, quem, quando, onde e por quê.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/jornal-maluco/jornal-maluco.pdf",
    imageUrl: "/atividades/ludica/jornal-maluco/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000098",
    title: "Casas das Palavras — Sinônimos e Antônimos",
    description: "Vinte palavras se mudam para a casa certa: a dos sinônimos ou a dos antônimos. Depois a criança escolhe dois pares e forma frases no caderno.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/casas-das-palavras-sinonimos-e-antonimos/casas-das-palavras-sinonimos-e-antonimos.pdf",
    imageUrl: "/atividades/ludica/casas-das-palavras-sinonimos-e-antonimos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000099",
    title: "Caça ao Texto",
    description: "Cinco trechos de uma história sobre o cachorro Max vêm embaralhados: a criança organiza na ordem certa, responde quatro perguntas sobre o texto montado e cria um final diferente.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-ao-texto/caca-ao-texto.pdf",
    imageUrl: "/atividades/ludica/caca-ao-texto/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000100",
    title: "Missão: Classificar Palavras",
    description: "Vinte palavras para recortar e distribuir entre substantivos, verbos e adjetivos, com a dica de que a mesma palavra muda de classe conforme o contexto.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/missao-classificar-palavras/missao-classificar-palavras.pdf",
    imageUrl: "/atividades/ludica/missao-classificar-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000101",
    title: "Varal das Frases — Palavras e Figuras",
    description: "Cinco figuras — cachorro, menino, menina, carro, sol — pedem a frase certa, montada com palavras e imagens recortadas. Depois cria outra frase com as mesmas palavras.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/varal-das-frases-palavras-e-figuras/varal-das-frases-palavras-e-figuras.pdf",
    imageUrl: "/atividades/ludica/varal-das-frases-palavras-e-figuras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000102",
    title: "A Ordem das Palavras",
    description: "Quatro frases embaralhadas para recortar, ordenar e reescrever, com a lembrança de que frase começa com maiúscula e termina com ponto. Fecha com um desenho de uma delas.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/a-ordem-das-palavras/a-ordem-das-palavras.pdf",
    imageUrl: "/atividades/ludica/a-ordem-das-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000103",
    title: "Varal das Frases — Leia em Voz Alta",
    description: "Três frases para montar no varal com palavras recortadas e ler em voz alta. No desafio, circula o sujeito e sublinha o verbo de cada frase formada.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/varal-das-frases-leia-em-voz-alta/varal-das-frases-leia-em-voz-alta.pdf",
    imageUrl: "/atividades/ludica/varal-das-frases-leia-em-voz-alta/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000104",
    title: "Monte a História",
    description: "Recorta três cenas e quatro frases da aventura de Pedro na chuva, organiza em começo, meio e fim, dá um título e reescreve a história completa em voz alta.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/monte-a-historia/monte-a-historia.pdf",
    imageUrl: "/atividades/ludica/monte-a-historia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000105",
    title: "Palavras com Mais de Um Sentido",
    description: "Seis frases e seis homônimas — pão, pneu, pássaro, copo, anzol, comer — para colar no lugar certo, mostrando que o sentido depende do contexto.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/palavras-com-mais-de-um-sentido/palavras-com-mais-de-um-sentido.pdf",
    imageUrl: "/atividades/ludica/palavras-com-mais-de-um-sentido/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000106",
    title: "Varal das Frases — Fique Atento",
    description: "Monta três frases no varal e confere numa lista de verificação se cada uma começa com maiúscula, tem sentido e termina com ponto final.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/varal-das-frases-fique-atento/varal-das-frases-fique-atento.pdf",
    imageUrl: "/atividades/ludica/varal-das-frases-fique-atento/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000107",
    title: "Onde Cabe? — Substantivos em Ação",
    description: "Oito figuras e quinze palavras para separar em pessoas, animais, lugares e objetos. Depois a criança escolhe duas de cada grupo e cria uma frase para cada.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/onde-cabe-substantivos-em-acao/onde-cabe-substantivos-em-acao.pdf",
    imageUrl: "/atividades/ludica/onde-cabe-substantivos-em-acao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000108",
    title: "Qual é a Classe?",
    description: "Vinte e cinco palavras ilustradas para distribuir entre substantivo, verbo, adjetivo, pronome e advérbio, com a definição de cada classe no topo da coluna.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/qual-e-a-classe/qual-e-a-classe.pdf",
    imageUrl: "/atividades/ludica/qual-e-a-classe/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000109",
    title: "Classifique as Palavras — Quatro Classes",
    description: "Vinte palavras para recortar e colar em substantivo, verbo, adjetivo ou advérbio. No desafio, escolhe três de cada categoria e cria uma frase criativa.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/classifique-as-palavras-quatro-classes/classifique-as-palavras-quatro-classes.pdf",
    imageUrl: "/atividades/ludica/classifique-as-palavras-quatro-classes/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000110",
    title: "Sílabas em Ação",
    description: "Trinta cartões de sílabas para juntar e formar palavras de animais, objetos, alimentos e lugares, colando cada uma no quadro certo e lendo em voz alta.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/silabas-em-acao/silabas-em-acao.pdf",
    imageUrl: "/atividades/ludica/silabas-em-acao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000111",
    title: "Palavras em Ordem",
    description: "Cinco frases ilustradas para montar com palavras recortadas na ordem certa. Depois a criança escolhe uma e escreve outra bem parecida.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/palavras-em-ordem/palavras-em-ordem.pdf",
    imageUrl: "/atividades/ludica/palavras-em-ordem/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000112",
    title: "Sons que Combinam",
    description: "Oito figuras — bola, gato, sol, flor, pato, cão, casa, praia — e dezoito palavras para colar as que rimam com cada uma. Trabalha consciência fonológica.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/sons-que-combinam/sons-que-combinam.pdf",
    imageUrl: "/atividades/ludica/sons-que-combinam/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000113",
    title: "Classifique as Palavras — Cinco Colunas",
    description: "Vinte palavras para separar em substantivos, verbos, adjetivos, pronomes e advérbios, com a definição de cada classe. Fecha escolhendo três colunas e criando uma frase.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/classifique-as-palavras-cinco-colunas/classifique-as-palavras-cinco-colunas.pdf",
    imageUrl: "/atividades/ludica/classifique-as-palavras-cinco-colunas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000114",
    title: "Sinônimos e Antônimos — Recorte e Cole",
    description: "Oito palavras numa tabela de três colunas: a criança cola o sinônimo e o antônimo de cada uma entre dezesseis cartões e depois forma frases com duas delas.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/sinonimos-e-antonimos-recorte-e-cole/sinonimos-e-antonimos-recorte-e-cole.pdf",
    imageUrl: "/atividades/ludica/sinonimos-e-antonimos-recorte-e-cole/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000115",
    title: "Ligue e Complete — Quem Faz o Quê?",
    description: "Combina seis substantivos com seis verbos e completa cada frase com o complemento certo — parque, livro, maçã, galho, cama, bola — lendo tudo em voz alta.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/ligue-e-complete-quem-faz-o-que/ligue-e-complete-quem-faz-o-que.pdf",
    imageUrl: "/atividades/ludica/ligue-e-complete-quem-faz-o-que/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000116",
    title: "Classifique as Palavras — Vinte Cartões",
    description: "Vinte cartões para colar em cinco colunas de classes gramaticais, com cinco espaços por coluna. No desafio, cria frases com duas palavras de cada uma.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/classifique-as-palavras-vinte-cartoes/classifique-as-palavras-vinte-cartoes.pdf",
    imageUrl: "/atividades/ludica/classifique-as-palavras-vinte-cartoes/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000117",
    title: "Caça ao Sinônimo",
    description: "Oito palavras ilustradas — feliz, casa, carro, presente, rápido, triste, amor, cachorro — e oito sinônimos para encontrar e colar. Fecha com duas frases usando os sinônimos.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-ao-sinonimo/caca-ao-sinonimo.pdf",
    imageUrl: "/atividades/ludica/caca-ao-sinonimo/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000118",
    title: "Classifique as Palavras — Com Interjeições",
    description: "Seis classes, interjeições incluídas, e vinte e quatro palavras para distribuir entre elas. Depois a criança escolhe três e cria uma frase para cada.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/classifique-as-palavras-com-interjeicoes/classifique-as-palavras-com-interjeicoes.pdf",
    imageUrl: "/atividades/ludica/classifique-as-palavras-com-interjeicoes/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000119",
    title: "Complete o Texto — Meu Dia na Escola",
    description: "Texto lacunado com cinco palavras dadas — escola, amigos, brincar, aprender, feliz — e um espaço grande para desenhar sobre o que foi lido.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/complete-o-texto-meu-dia-na-escola/complete-o-texto-meu-dia-na-escola.pdf",
    imageUrl: "/atividades/ludica/complete-o-texto-meu-dia-na-escola/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000120",
    title: "Caça-Palavras Temático — Escola e Amizade",
    description: "Dez palavras sobre escola, estudo e convivência escondidas na horizontal, na vertical e na diagonal, numa grade de doze colunas.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-palavras-tematico-escola-e-amizade/caca-palavras-tematico-escola-e-amizade.pdf",
    imageUrl: "/atividades/ludica/caca-palavras-tematico-escola-e-amizade/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000121",
    title: "Complete com as Palavras Adequadas",
    description: "Dez frases ilustradas para completar com as palavras do quadro, cada uma apoiada num desenho que ajuda a criança a escolher certo.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/complete-com-as-palavras-adequadas/complete-com-as-palavras-adequadas.pdf",
    imageUrl: "/atividades/ludica/complete-com-as-palavras-adequadas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000122",
    title: "Oficina de Língua Portuguesa — Nove Desafios",
    description: "Uma folha com nove seções: caça-palavras, completar frases, separar sílabas, formar frases a partir de imagem, achar o intruso, ordenar palavras, ligar sinônimos, escrever antônimos e completar um texto.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/oficina-de-lingua-portuguesa-nove-desafios/oficina-de-lingua-portuguesa-nove-desafios.pdf",
    imageUrl: "/atividades/ludica/oficina-de-lingua-portuguesa-nove-desafios/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000123",
    title: "Caça-Palavras Temático — Forme Frases",
    description: "Dez palavras sobre escola e futuro na grade; depois a criança escolhe três para escrever frases e uma para desenhar e descrever.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-palavras-tematico-forme-frases/caca-palavras-tematico-forme-frases.pdf",
    imageUrl: "/atividades/ludica/caca-palavras-tematico-forme-frases/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000124",
    title: "Complete com as Palavras — Dez Frases",
    description: "Dez frases sobre o dia a dia para completar com as palavras do quadro. No desafio, reescreve três delas com outras palavras mantendo o mesmo sentido.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/complete-com-as-palavras-dez-frases/complete-com-as-palavras-dez-frases.pdf",
    imageUrl: "/atividades/ludica/complete-com-as-palavras-dez-frases/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000125",
    title: "Leitura e Interpretação — O Cachorro e o Balão",
    description: "Lê a história da cachorrinha Luna e do balão preso na árvore e responde oito perguntas, da mais direta à de opinião, fechando com um desafio de imaginação.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/leitura-e-interpretacao-o-cachorro-e-o-balao/leitura-e-interpretacao-o-cachorro-e-o-balao.pdf",
    imageUrl: "/atividades/ludica/leitura-e-interpretacao-o-cachorro-e-o-balao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000126",
    title: "Leitura com Atenção — O Livro Mágico",
    description: "Sobre o conto do livro que transporta Lívia para outro mundo: oito questões que misturam pergunta aberta, múltipla escolha, marcação de características e opinião.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/leitura-com-atencao-o-livro-magico/leitura-com-atencao-o-livro-magico.pdf",
    imageUrl: "/atividades/ludica/leitura-com-atencao-o-livro-magico/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000127",
    title: "Caça-Palavras Temático — Palavras e Conquistas",
    description: "Oito palavras sobre escola, família e sonhos na grade; depois a criança escreve três frases e responde qual palavra mais combina com ela e por quê.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-palavras-tematico-palavras-e-conquistas/caca-palavras-tematico-palavras-e-conquistas.pdf",
    imageUrl: "/atividades/ludica/caca-palavras-tematico-palavras-e-conquistas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000128",
    title: "Caça-Palavras dos Animais",
    description: "Dez animais escondidos na grade, mais três seções de ortografia e escrita: completar com S, SS, C ou Ç, separar sílabas e formar frases criativas.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-palavras-dos-animais/caca-palavras-dos-animais.pdf",
    imageUrl: "/atividades/ludica/caca-palavras-dos-animais/capa.webp",
  }
];
