// ═══════════════════════════════════════════════════════════════════════════
// GERADO por scripts/build-atividades.mjs a partir de
// scripts/atividades.manifest.json. Não editar à mão: rode
//   node scripts/build-atividades.mjs
//
// É o acervo que a Home mostra quando o banco volta vazio. Os uuids são os
// mesmos da migration 012, então favoritar no fallback e no banco dá no
// mesmo registro.
// ═══════════════════════════════════════════════════════════════════════════

import type { Resource } from "./types";

export const atividades: Resource[] = [
  {
    id: "a01a7eca-0002-4000-8000-000000000001",
    title: "1º Ano — Gramática: Monte a Palavra",
    description: "Três jogos de recortar e colar: montar palavras a partir de sílabas, caçar as vogais que faltam e organizar palavras soltas em frases. Trabalha consciência fonológica e formação de frases.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/1o-ano-gramatica-monte-a-palavra/1o-ano-gramatica-monte-a-palavra.pdf",
    imageUrl: "/atividades/ludica/1o-ano-gramatica-monte-a-palavra/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000002",
    title: "1º Ano — Redação: Histórias Incríveis",
    description: "Sorteia personagem, lugar e objeto recortados para inventar uma história maluca, ordena as cenas de uma narrativa e monta a própria história em quatro quadros com desenho e escrita.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/1o-ano-redacao-historias-incriveis/1o-ano-redacao-historias-incriveis.pdf",
    imageUrl: "/atividades/ludica/1o-ano-redacao-historias-incriveis/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000003",
    title: "1º Ano — Interpretação: Detetive da História",
    description: "Lê um texto curto e cola as respostas de quem, onde e o quê; liga cada personagem à sua ação e recorta três cenas para colocar na ordem certa.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/1o-ano-interpretacao-detetive-da-historia/1o-ano-interpretacao-detetive-da-historia.pdf",
    imageUrl: "/atividades/ludica/1o-ano-interpretacao-detetive-da-historia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000004",
    title: "2º Ano — Gramática: A Casa dos Substantivos",
    description: "Classifica doze palavras em pessoas, animais, objetos e lugares, identifica o verbo que indica a ação em cada frase e combina adjetivos com os substantivos certos.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/2o-ano-gramatica-casa-dos-substantivos/2o-ano-gramatica-casa-dos-substantivos.pdf",
    imageUrl: "/atividades/ludica/2o-ano-gramatica-casa-dos-substantivos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000005",
    title: "2º Ano — Redação: Fábrica de Histórias",
    description: "Combina personagem, lugar e acontecimento recortados, ordena cartas para montar o enredo e reescreve o final de uma história dada. Trabalha estrutura narrativa e criatividade.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/2o-ano-redacao-fabrica-de-historias/2o-ano-redacao-fabrica-de-historias.pdf",
    imageUrl: "/atividades/ludica/2o-ano-redacao-fabrica-de-historias/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000006",
    title: "2º Ano — Interpretação: Mapa da História",
    description: "Responde a perguntas de quem, onde e quando sobre um texto curto, desembaralha as cenas de uma narrativa e preenche o mapa da história com personagens, lugar, problema e desfecho.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/2o-ano-interpretacao-mapa-da-historia/2o-ano-interpretacao-mapa-da-historia.pdf",
    imageUrl: "/atividades/ludica/2o-ano-interpretacao-mapa-da-historia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000007",
    title: "3º Ano — Gramática: Detetives da Pontuação",
    description: "Recorta os sinais de pontuação e cola nos lugares certos de um texto sem pontuação, reescreve o texto pontuado e completa frases com o sinal que falta.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/3o-ano-gramatica-detetives-da-pontuacao/3o-ano-gramatica-detetives-da-pontuacao.pdf",
    imageUrl: "/atividades/ludica/3o-ano-gramatica-detetives-da-pontuacao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000008",
    title: "3º Ano — Redação: Meu Primeiro Jornal",
    description: "Cria um personagem em ficha e desenho, dá continuidade a uma história começada e escreve uma notícia seguindo a estrutura de título, quem, onde, quando, o quê, por quê e como.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/3o-ano-redacao-meu-primeiro-jornal/3o-ano-redacao-meu-primeiro-jornal.pdf",
    imageUrl: "/atividades/ludica/3o-ano-redacao-meu-primeiro-jornal/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000009",
    title: "3º Ano — Interpretação: O Cachorro Fiel",
    description: "Lê o texto sobre o cachorro fiel e responde cinco perguntas, marca verdadeiro ou falso, preenche o mapa da história com problema e lição e separa palavras em sílabas.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/3o-ano-interpretacao-o-cachorro-fiel/3o-ano-interpretacao-o-cachorro-fiel.pdf",
    imageUrl: "/atividades/ludica/3o-ano-interpretacao-o-cachorro-fiel/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000010",
    title: "4º Ano — Gramática: As Palavras Têm Poder",
    description: "Seis blocos de gramática numa folha só: classes de palavras, substantivos comuns e próprios, tempos verbais, sinais de pontuação, caça ao erro e formação de frases.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/4o-ano-gramatica-as-palavras-tem-poder/4o-ano-gramatica-as-palavras-tem-poder.pdf",
    imageUrl: "/atividades/ludica/4o-ano-gramatica-as-palavras-tem-poder/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000011",
    title: "4º Ano — Redação: Crie seu Personagem",
    description: "Preenche a ficha completa de um personagem, escreve uma história com começo, meio e fim e produz uma página de diário. Inclui tabela de revisão da própria produção.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/4o-ano-redacao-crie-seu-personagem/4o-ano-redacao-crie-seu-personagem.pdf",
    imageUrl: "/atividades/ludica/4o-ano-redacao-crie-seu-personagem/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000012",
    title: "4º Ano — Interpretação: A Importância das Abelhas",
    description: "Sete blocos sobre um texto informativo: perguntas de compreensão, verdadeiro ou falso, antônimos, inferência, ordem dos fatos, ligação de ideias e produção de opinião.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/4o-ano-interpretacao-a-importancia-das-abelhas/4o-ano-interpretacao-a-importancia-das-abelhas.pdf",
    imageUrl: "/atividades/ludica/4o-ano-interpretacao-a-importancia-das-abelhas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000013",
    title: "5º Ano — Gramática: Classes e Concordância",
    description: "Classes de palavras, substantivos concretos e abstratos, figuras de linguagem, sujeito e predicado, tempos e modos verbais e correção de erros de concordância.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/5o-ano-gramatica-classes-e-concordancia/5o-ano-gramatica-classes-e-concordancia.pdf",
    imageUrl: "/atividades/ludica/5o-ano-gramatica-classes-e-concordancia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000014",
    title: "5º Ano — Redação: Planeje sua História",
    description: "Cria o personagem, planeja a história em começo, meio e fim antes de escrever e produz o texto final. Fecha com uma tabela de autoavaliação da produção.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/5o-ano-redacao-planeje-sua-historia/5o-ano-redacao-planeje-sua-historia.pdf",
    imageUrl: "/atividades/ludica/5o-ano-redacao-planeje-sua-historia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000015",
    title: "5º Ano — Interpretação: A Importância da Leitura",
    description: "Oito blocos sobre um texto argumentativo: compreensão, verdadeiro ou falso, inferências, antônimos, ordem dos fatos, palavras no contexto e produção de opinião.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/5o-ano-interpretacao-a-importancia-da-leitura/5o-ano-interpretacao-a-importancia-da-leitura.pdf",
    imageUrl: "/atividades/ludica/5o-ano-interpretacao-a-importancia-da-leitura/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000016",
    title: "Caça ao Tesouro das Palavras",
    description: "Seis pistas descrevem objetos do dia a dia. A criança recorta as palavras e cola cada tesouro no lugar certo do mapa pirata. Trabalha leitura, vocabulário e associação.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/caca-ao-tesouro-das-palavras/caca-ao-tesouro-das-palavras.pdf",
    imageUrl: "/atividades/ludica/caca-ao-tesouro-das-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000017",
    title: "Bingo das Palavras",
    description: "Cartela de dezesseis palavras com imagem e dez pistas para o professor ler em voz alta. Inclui fichas recortáveis para marcar e um desafio de criar frases com três palavras sorteadas.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/bingo-das-palavras/bingo-das-palavras.pdf",
    imageUrl: "/atividades/ludica/bingo-das-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000018",
    title: "Memória de Palavras e Imagens",
    description: "Vinte cartas para recortar formam dez pares de palavra e imagem. Depois do jogo da memória, a criança escolhe três pares e escreve uma frase ou história curta.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/memoria-de-palavras-e-imagens/memoria-de-palavras-e-imagens.pdf",
    imageUrl: "/atividades/ludica/memoria-de-palavras-e-imagens/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000019",
    title: "Dominó de Palavras",
    description: "Peças de imagem, palavra e definição para recortar e encaixar como um dominó, com tabuleiro em branco para montar as combinações. Trabalha leitura e significado.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/domino-de-palavras/domino-de-palavras.pdf",
    imageUrl: "/atividades/ludica/domino-de-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000020",
    title: "Roleta da Imaginação",
    description: "Roleta de quatro quadrantes — personagem, lugar, objeto e ação — montada com colchete. A criança gira, registra o sorteio na ficha e escreve a história que saiu.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/roleta-da-imaginacao/roleta-da-imaginacao.pdf",
    imageUrl: "/atividades/ludica/roleta-da-imaginacao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000021",
    title: "Quebra-Cabeça da História",
    description: "Quatro cenas de uma história para recortar, organizar na ordem que faz sentido e colar. Depois a criança reconta a narrativa com as próprias palavras.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/quebra-cabeca-da-historia/quebra-cabeca-da-historia.pdf",
    imageUrl: "/atividades/ludica/quebra-cabeca-da-historia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000022",
    title: "Quem Sou Eu?",
    description: "Quatro conjuntos de pistas descrevem um objeto ou animal. A criança recorta as oito cartas e cola a resposta certa em cada quadro, depois cria uma frase com ela.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/quem-sou-eu/quem-sou-eu.pdf",
    imageUrl: "/atividades/ludica/quem-sou-eu/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000023",
    title: "Complete o Desenho e Conte",
    description: "Quatro cenas incompletas para a criança terminar de desenhar, com um banco de dez ideias ilustradas. Em seguida escreve uma frase, legenda ou história curta sobre o que criou.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/complete-o-desenho-e-conte/complete-o-desenho-e-conte.pdf",
    imageUrl: "/atividades/ludica/complete-o-desenho-e-conte/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000024",
    title: "Trilha das Palavras",
    description: "Tabuleiro de dezenove casas com desafios de leitura, fala e criatividade, com peões e dado para recortar e montar. Pode ser jogado em dupla, em grupo ou sozinho.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/trilha-das-palavras/trilha-das-palavras.pdf",
    imageUrl: "/atividades/ludica/trilha-das-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000025",
    title: "Desafio das Rimas",
    description: "Cinco pares que rimam para ligar e dez cartas para recortar e juntar. Fecha com a escrita de uma frase e de um versinho usando o par favorito.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "20 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/desafio-das-rimas/desafio-das-rimas.pdf",
    imageUrl: "/atividades/ludica/desafio-das-rimas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000026",
    title: "Monstro das Emoções",
    description: "Monta um monstrinho com cabeça, olhos, boca, braços, pernas e acessórios recortáveis, escolhe entre seis emoções e escreve como ele está se sentindo e por quê.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/monstro-das-emocoes/monstro-das-emocoes.pdf",
    imageUrl: "/atividades/ludica/monstro-das-emocoes/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000027",
    title: "Monstro das Emoções — Monte e Conte",
    description: "Versão ampliada: monta o monstro com as peças recortáveis, escolhe a emoção numa escala de seis e responde por que ele se sente assim, o que aconteceu e o que pode melhorar.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/monstro-das-emocoes-monte-e-conte/monstro-das-emocoes-monte-e-conte.pdf",
    imageUrl: "/atividades/ludica/monstro-das-emocoes-monte-e-conte/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000028",
    title: "Missão dos Piratas",
    description: "Seis pistas indicam o caminho até o tesouro escondido. A criança recorta navio, caverna, vulcão, ponte e baú, monta o mapa na ordem certa e responde ao desafio extra.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/missao-dos-piratas/missao-dos-piratas.pdf",
    imageUrl: "/atividades/ludica/missao-dos-piratas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000029",
    title: "Parque dos Dinossauros",
    description: "Nove dinossauros para recortar e colar no habitat correto — floresta, vulcão, lago, deserto ou caverna — com cards explicativos, três perguntas e o desafio de criar um dino inédito.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/parque-dos-dinossauros/parque-dos-dinossauros.pdf",
    imageUrl: "/atividades/ludica/parque-dos-dinossauros/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000030",
    title: "Laboratório do Cientista",
    description: "Combina tubos de ensaio, ingredientes e equipamentos recortáveis em três experimentos, preenche a ficha da invenção e desenha o resultado. Inclui cartas-surpresa que mudam tudo.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/laboratorio-do-cientista/laboratorio-do-cientista.pdf",
    imageUrl: "/atividades/ludica/laboratorio-do-cientista/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000031",
    title: "Fábrica de Super-Heróis",
    description: "Monta o herói com máscara, capa, uniforme, acessórios e símbolo recortáveis, escolhe os superpoderes, preenche a ficha e escreve uma aventura cumprindo as missões do dia.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/fabrica-de-super-herois/fabrica-de-super-herois.pdf",
    imageUrl: "/atividades/ludica/fabrica-de-super-herois/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000032",
    title: "Construa um Castelo",
    description: "Torres, muralhas, portões, bandeiras, decorações e personagens para recortar e montar o castelo. Depois a criança descreve quem mora nele, desenha o interior e cria o brasão.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/construa-um-castelo/construa-um-castelo.pdf",
    imageUrl: "/atividades/ludica/construa-um-castelo/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000033",
    title: "Safari dos Animais",
    description: "Dez animais para recortar e colar no habitat certo — savana, floresta, oceano, deserto e polo norte —, três perguntas de observação, jogo da memória e um animal inventado.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/safari-dos-animais/safari-dos-animais.pdf",
    imageUrl: "/atividades/ludica/safari-dos-animais/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000034",
    title: "Mercado Divertido",
    description: "Monta a cesta seguindo três listas de compras, recorta produtos por setor — hortifruti, laticínios, padaria, higiene e bebidas — e trabalha etiquetas de preço com cartas-surpresa.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/mercado-divertido/mercado-divertido.pdf",
    imageUrl: "/atividades/ludica/mercado-divertido/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000035",
    title: "Restaurante Maluco",
    description: "Três clientes fazem pedidos e a criança monta cada prato com ingredientes recortáveis, escreve o menu do dia e encara o desafio do chef com as cartas-surpresa.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/restaurante-maluco/restaurante-maluco.pdf",
    imageUrl: "/atividades/ludica/restaurante-maluco/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000036",
    title: "Missão dos Bombeiros",
    description: "Monta a cena de resgate com veículos, equipamentos e personagens recortáveis, numera o plano de resgate na ordem correta e escreve o que aconteceu. Ensina quando ligar 193.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/missao-dos-bombeiros/missao-dos-bombeiros.pdf",
    imageUrl: "/atividades/ludica/missao-dos-bombeiros/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000037",
    title: "Escola de Magia",
    description: "Cria o próprio mago escolhendo chapéu, varinha, livro e cristal, inventa três poções e um feitiço, joga a memória mágica e escreve a aventura na escola de magia.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/escola-de-magia/escola-de-magia.pdf",
    imageUrl: "/atividades/ludica/escola-de-magia/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000038",
    title: "Navio Fantasma",
    description: "Mistério de detetive a bordo: monta a cena com as peças recortáveis, resolve o enigma do código e preenche o diário do pirata contando o que descobriu.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/navio-fantasma/navio-fantasma.pdf",
    imageUrl: "/atividades/ludica/navio-fantasma/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000039",
    title: "Acampamento na Floresta",
    description: "Monta o acampamento, escolhe seis itens essenciais para a mochila do explorador e registra a aventura no diário. Inclui cartas-surpresa e jogo da memória.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/acampamento-na-floresta/acampamento-na-floresta.pdf",
    imageUrl: "/atividades/ludica/acampamento-na-floresta/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000040",
    title: "Resgate no Fundo do Mar",
    description: "Monta o cenário marinho, separa o que protege do que polui o mar, numera o plano de resgate e resolve o enigma do tesouro. Trabalha consciência ambiental.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/resgate-no-fundo-do-mar/resgate-no-fundo-do-mar.pdf",
    imageUrl: "/atividades/ludica/resgate-no-fundo-do-mar/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000041",
    title: "Óculos do Detetive",
    description: "Recorta os óculos de lentes vermelha e azul, levanta três abas de pistas em camadas e descobre quem pegou o livro mágico da biblioteca. Trabalha inferência e dedução.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/oculos-do-detetive/oculos-do-detetive.pdf",
    imageUrl: "/atividades/ludica/oculos-do-detetive/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000042",
    title: "Máquina das Escolhas",
    description: "Três roletas presas com clipe sorteiam personagem, lugar e missão. A criança gira, combina os elementos e escreve a aventura que saiu no sorteio.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/maquina-das-escolhas/maquina-das-escolhas.pdf",
    imageUrl: "/atividades/ludica/maquina-das-escolhas/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000043",
    title: "Cidade Pop-Up",
    description: "Seis prédios dobráveis, personagens e veículos para recortar e montar uma cidade em três dimensões sobre a base. Depois a criança cria histórias que acontecem nela.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/cidade-pop-up/cidade-pop-up.pdf",
    imageUrl: "/atividades/ludica/cidade-pop-up/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000044",
    title: "Trilha da Ilha do Tesouro",
    description: "Jogo de tabuleiro completo para montar: dado de dobrar, marcadores em base de barco, cartas de aventura e envelope do tesouro. Trabalha leitura de instruções e jogo em grupo.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "40 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/trilha-da-ilha-do-tesouro/trilha-da-ilha-do-tesouro.pdf",
    imageUrl: "/atividades/ludica/trilha-da-ilha-do-tesouro/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000045",
    title: "Hospital das Frases",
    description: "Cinco frases doentes para diagnosticar: falta de maiúscula, acentuação, pontuação e concordância. A criança encontra o erro e cola a correção recortada.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/hospital-das-frases/hospital-das-frases.pdf",
    imageUrl: "/atividades/ludica/hospital-das-frases/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000046",
    title: "Guarda-Roupa das Palavras",
    description: "Vinte palavras para recortar e guardar na gaveta certa: substantivo, verbo, adjetivo ou pronome. Fecha com a escrita de quatro frases usando as classes trabalhadas.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/guarda-roupa-das-palavras/guarda-roupa-das-palavras.pdf",
    imageUrl: "/atividades/ludica/guarda-roupa-das-palavras/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000047",
    title: "Semáforo da Pontuação",
    description: "Cola o sinal certo em cinco frases e depois reescreve duas delas trocando a pontuação para ver como o sentido muda. Trabalha ponto, vírgula, interrogação e exclamação.",
    category: "ludica",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/semaforo-da-pontuacao/semaforo-da-pontuacao.pdf",
    imageUrl: "/atividades/ludica/semaforo-da-pontuacao/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000048",
    title: "História por Imagens",
    description: "Quatro cenas para recortar e ordenar em começo, meio e fim. Com a sequência montada, a criança escreve a narrativa completa em quatro parágrafos.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/historia-por-imagens/historia-por-imagens.pdf",
    imageUrl: "/atividades/ludica/historia-por-imagens/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000049",
    title: "Diário de um Personagem",
    description: "Escolhe um entre quatro personagens, cola a figura e escreve uma página de diário em primeira pessoa. Inclui autoavaliação da produção escrita.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/diario-de-um-personagem/diario-de-um-personagem.pdf",
    imageUrl: "/atividades/ludica/diario-de-um-personagem/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000050",
    title: "Correio das Frases",
    description: "Oito frases para recortar e entregar no envelope certo: pergunta, ordem, exclamação ou afirmação. Depois a criança escreve uma frase de cada tipo.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/correio-das-frases/correio-das-frases.pdf",
    imageUrl: "/atividades/ludica/correio-das-frases/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000051",
    title: "Fábrica de Personagens",
    description: "Escolhe aparência, personalidade, sonho, medo e objetivo, monta a ficha do personagem e escreve um texto apresentando-o. Base para qualquer produção narrativa.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/fabrica-de-personagens/fabrica-de-personagens.pdf",
    imageUrl: "/atividades/ludica/fabrica-de-personagens/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000052",
    title: "Quebra-Cabeça dos Parágrafos",
    description: "Cinco parágrafos embaralhados para recortar e colar na ordem que forma o texto. A criança cria um título e responde sobre a lição que a história deixa.",
    category: "interpretacao-texto",
    type: "pdf",
    ageRange: "9-11",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/quebra-cabeca-dos-paragrafos/quebra-cabeca-dos-paragrafos.pdf",
    imageUrl: "/atividades/ludica/quebra-cabeca-dos-paragrafos/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000053",
    title: "Máquina do Antes e Depois",
    description: "Dez frases ilustradas para recortar e colar na coluna do passado, do presente ou do futuro. Fecha reescrevendo duas delas nos três tempos verbais.",
    category: "ludica",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/maquina-do-antes-e-depois/maquina-do-antes-e-depois.pdf",
    imageUrl: "/atividades/ludica/maquina-do-antes-e-depois/capa.webp",
  },
  {
    id: "a01a7eca-0002-4000-8000-000000000054",
    title: "Cartas das Emoções",
    description: "Combina personagem, situação e emoção e escreve o que aconteceu, como se sentiu, por quê e o que ajudaria. Trabalha vocabulário emocional e produção escrita.",
    category: "producao-texto",
    type: "pdf",
    ageRange: "6-8",
    duration: "30 min",
    downloads: 0,
    rating: 0,
    author: "Aulateca",
    fileUrl: "ludica/cartas-das-emocoes/cartas-das-emocoes.pdf",
    imageUrl: "/atividades/ludica/cartas-das-emocoes/capa.webp",
  }
];
