-- ════════════════════════════════════════════════════════════════════════════
-- 012 — Acervo real: as fichas lúdicas em PDF da pasta do gestor.
--
-- GERADO por scripts/build-atividades.mjs a partir de
-- scripts/atividades.manifest.json. Não editar à mão: rode o script.
--
-- file_url NÃO é uma URL: é o caminho do PDF dentro do bucket privado
-- `atividades` (migration 015). O frontend troca isso por uma URL assinada de
-- curta duração, e só para quem tem acesso pago. image_url continua sendo URL
-- pública de verdade — a capa é vitrine.
--
-- Idempotente via uuids fixos + on conflict do nothing: rodar de novo não
-- duplica nem sobrescreve edições feitas pelo /admin depois.
-- ════════════════════════════════════════════════════════════════════════════

insert into public.resources
  (id, title, description, category, type, age_range, duration, file_url, image_url, author_name)
values
  ('a01a7eca-0002-4000-8000-000000000001', '1º Ano — Gramática: Monte a Palavra', 'Três jogos de recortar e colar: montar palavras a partir de sílabas, caçar as vogais que faltam e organizar palavras soltas em frases. Trabalha consciência fonológica e formação de frases.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/1o-ano-gramatica-monte-a-palavra/1o-ano-gramatica-monte-a-palavra.pdf', '/atividades/ludica/1o-ano-gramatica-monte-a-palavra/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000002', '1º Ano — Redação: Histórias Incríveis', 'Sorteia personagem, lugar e objeto recortados para inventar uma história maluca, ordena as cenas de uma narrativa e monta a própria história em quatro quadros com desenho e escrita.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/1o-ano-redacao-historias-incriveis/1o-ano-redacao-historias-incriveis.pdf', '/atividades/ludica/1o-ano-redacao-historias-incriveis/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000003', '1º Ano — Interpretação: Detetive da História', 'Lê um texto curto e cola as respostas de quem, onde e o quê; liga cada personagem à sua ação e recorta três cenas para colocar na ordem certa.', 'interpretacao-texto', 'pdf', '6-8', '30 min', 'ludica/1o-ano-interpretacao-detetive-da-historia/1o-ano-interpretacao-detetive-da-historia.pdf', '/atividades/ludica/1o-ano-interpretacao-detetive-da-historia/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000004', '2º Ano — Gramática: A Casa dos Substantivos', 'Classifica doze palavras em pessoas, animais, objetos e lugares, identifica o verbo que indica a ação em cada frase e combina adjetivos com os substantivos certos.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/2o-ano-gramatica-casa-dos-substantivos/2o-ano-gramatica-casa-dos-substantivos.pdf', '/atividades/ludica/2o-ano-gramatica-casa-dos-substantivos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000005', '2º Ano — Redação: Fábrica de Histórias', 'Combina personagem, lugar e acontecimento recortados, ordena cartas para montar o enredo e reescreve o final de uma história dada. Trabalha estrutura narrativa e criatividade.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/2o-ano-redacao-fabrica-de-historias/2o-ano-redacao-fabrica-de-historias.pdf', '/atividades/ludica/2o-ano-redacao-fabrica-de-historias/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000006', '2º Ano — Interpretação: Mapa da História', 'Responde a perguntas de quem, onde e quando sobre um texto curto, desembaralha as cenas de uma narrativa e preenche o mapa da história com personagens, lugar, problema e desfecho.', 'interpretacao-texto', 'pdf', '6-8', '30 min', 'ludica/2o-ano-interpretacao-mapa-da-historia/2o-ano-interpretacao-mapa-da-historia.pdf', '/atividades/ludica/2o-ano-interpretacao-mapa-da-historia/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000007', '3º Ano — Gramática: Detetives da Pontuação', 'Recorta os sinais de pontuação e cola nos lugares certos de um texto sem pontuação, reescreve o texto pontuado e completa frases com o sinal que falta.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/3o-ano-gramatica-detetives-da-pontuacao/3o-ano-gramatica-detetives-da-pontuacao.pdf', '/atividades/ludica/3o-ano-gramatica-detetives-da-pontuacao/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000008', '3º Ano — Redação: Meu Primeiro Jornal', 'Cria um personagem em ficha e desenho, dá continuidade a uma história começada e escreve uma notícia seguindo a estrutura de título, quem, onde, quando, o quê, por quê e como.', 'producao-texto', 'pdf', '6-8', '40 min', 'ludica/3o-ano-redacao-meu-primeiro-jornal/3o-ano-redacao-meu-primeiro-jornal.pdf', '/atividades/ludica/3o-ano-redacao-meu-primeiro-jornal/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000009', '3º Ano — Interpretação: O Cachorro Fiel', 'Lê o texto sobre o cachorro fiel e responde cinco perguntas, marca verdadeiro ou falso, preenche o mapa da história com problema e lição e separa palavras em sílabas.', 'interpretacao-texto', 'pdf', '6-8', '30 min', 'ludica/3o-ano-interpretacao-o-cachorro-fiel/3o-ano-interpretacao-o-cachorro-fiel.pdf', '/atividades/ludica/3o-ano-interpretacao-o-cachorro-fiel/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000010', '4º Ano — Gramática: As Palavras Têm Poder', 'Seis blocos de gramática numa folha só: classes de palavras, substantivos comuns e próprios, tempos verbais, sinais de pontuação, caça ao erro e formação de frases.', 'ludica', 'pdf', '9-11', '40 min', 'ludica/4o-ano-gramatica-as-palavras-tem-poder/4o-ano-gramatica-as-palavras-tem-poder.pdf', '/atividades/ludica/4o-ano-gramatica-as-palavras-tem-poder/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000011', '4º Ano — Redação: Crie seu Personagem', 'Preenche a ficha completa de um personagem, escreve uma história com começo, meio e fim e produz uma página de diário. Inclui tabela de revisão da própria produção.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/4o-ano-redacao-crie-seu-personagem/4o-ano-redacao-crie-seu-personagem.pdf', '/atividades/ludica/4o-ano-redacao-crie-seu-personagem/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000012', '4º Ano — Interpretação: A Importância das Abelhas', 'Sete blocos sobre um texto informativo: perguntas de compreensão, verdadeiro ou falso, antônimos, inferência, ordem dos fatos, ligação de ideias e produção de opinião.', 'interpretacao-texto', 'pdf', '9-11', '40 min', 'ludica/4o-ano-interpretacao-a-importancia-das-abelhas/4o-ano-interpretacao-a-importancia-das-abelhas.pdf', '/atividades/ludica/4o-ano-interpretacao-a-importancia-das-abelhas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000013', '5º Ano — Gramática: Classes e Concordância', 'Classes de palavras, substantivos concretos e abstratos, figuras de linguagem, sujeito e predicado, tempos e modos verbais e correção de erros de concordância.', 'ludica', 'pdf', '9-11', '40 min', 'ludica/5o-ano-gramatica-classes-e-concordancia/5o-ano-gramatica-classes-e-concordancia.pdf', '/atividades/ludica/5o-ano-gramatica-classes-e-concordancia/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000014', '5º Ano — Redação: Planeje sua História', 'Cria o personagem, planeja a história em começo, meio e fim antes de escrever e produz o texto final. Fecha com uma tabela de autoavaliação da produção.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/5o-ano-redacao-planeje-sua-historia/5o-ano-redacao-planeje-sua-historia.pdf', '/atividades/ludica/5o-ano-redacao-planeje-sua-historia/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000015', '5º Ano — Interpretação: A Importância da Leitura', 'Oito blocos sobre um texto argumentativo: compreensão, verdadeiro ou falso, inferências, antônimos, ordem dos fatos, palavras no contexto e produção de opinião.', 'interpretacao-texto', 'pdf', '9-11', '40 min', 'ludica/5o-ano-interpretacao-a-importancia-da-leitura/5o-ano-interpretacao-a-importancia-da-leitura.pdf', '/atividades/ludica/5o-ano-interpretacao-a-importancia-da-leitura/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000016', 'Caça ao Tesouro das Palavras', 'Seis pistas descrevem objetos do dia a dia. A criança recorta as palavras e cola cada tesouro no lugar certo do mapa pirata. Trabalha leitura, vocabulário e associação.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/caca-ao-tesouro-das-palavras/caca-ao-tesouro-das-palavras.pdf', '/atividades/ludica/caca-ao-tesouro-das-palavras/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000017', 'Bingo das Palavras', 'Cartela de dezesseis palavras com imagem e dez pistas para o professor ler em voz alta. Inclui fichas recortáveis para marcar e um desafio de criar frases com três palavras sorteadas.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/bingo-das-palavras/bingo-das-palavras.pdf', '/atividades/ludica/bingo-das-palavras/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000018', 'Memória de Palavras e Imagens', 'Vinte cartas para recortar formam dez pares de palavra e imagem. Depois do jogo da memória, a criança escolhe três pares e escreve uma frase ou história curta.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/memoria-de-palavras-e-imagens/memoria-de-palavras-e-imagens.pdf', '/atividades/ludica/memoria-de-palavras-e-imagens/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000019', 'Dominó de Palavras', 'Peças de imagem, palavra e definição para recortar e encaixar como um dominó, com tabuleiro em branco para montar as combinações. Trabalha leitura e significado.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/domino-de-palavras/domino-de-palavras.pdf', '/atividades/ludica/domino-de-palavras/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000020', 'Roleta da Imaginação', 'Roleta de quatro quadrantes — personagem, lugar, objeto e ação — montada com colchete. A criança gira, registra o sorteio na ficha e escreve a história que saiu.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/roleta-da-imaginacao/roleta-da-imaginacao.pdf', '/atividades/ludica/roleta-da-imaginacao/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000021', 'Quebra-Cabeça da História', 'Quatro cenas de uma história para recortar, organizar na ordem que faz sentido e colar. Depois a criança reconta a narrativa com as próprias palavras.', 'producao-texto', 'pdf', '6-8', '20 min', 'ludica/quebra-cabeca-da-historia/quebra-cabeca-da-historia.pdf', '/atividades/ludica/quebra-cabeca-da-historia/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000022', 'Quem Sou Eu?', 'Quatro conjuntos de pistas descrevem um objeto ou animal. A criança recorta as oito cartas e cola a resposta certa em cada quadro, depois cria uma frase com ela.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/quem-sou-eu/quem-sou-eu.pdf', '/atividades/ludica/quem-sou-eu/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000023', 'Complete o Desenho e Conte', 'Quatro cenas incompletas para a criança terminar de desenhar, com um banco de dez ideias ilustradas. Em seguida escreve uma frase, legenda ou história curta sobre o que criou.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/complete-o-desenho-e-conte/complete-o-desenho-e-conte.pdf', '/atividades/ludica/complete-o-desenho-e-conte/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000024', 'Trilha das Palavras', 'Tabuleiro de dezenove casas com desafios de leitura, fala e criatividade, com peões e dado para recortar e montar. Pode ser jogado em dupla, em grupo ou sozinho.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/trilha-das-palavras/trilha-das-palavras.pdf', '/atividades/ludica/trilha-das-palavras/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000025', 'Desafio das Rimas', 'Cinco pares que rimam para ligar e dez cartas para recortar e juntar. Fecha com a escrita de uma frase e de um versinho usando o par favorito.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/desafio-das-rimas/desafio-das-rimas.pdf', '/atividades/ludica/desafio-das-rimas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000026', 'Monstro das Emoções', 'Monta um monstrinho com cabeça, olhos, boca, braços, pernas e acessórios recortáveis, escolhe entre seis emoções e escreve como ele está se sentindo e por quê.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/monstro-das-emocoes/monstro-das-emocoes.pdf', '/atividades/ludica/monstro-das-emocoes/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000027', 'Monstro das Emoções — Monte e Conte', 'Versão ampliada: monta o monstro com as peças recortáveis, escolhe a emoção numa escala de seis e responde por que ele se sente assim, o que aconteceu e o que pode melhorar.', 'producao-texto', 'pdf', '6-8', '40 min', 'ludica/monstro-das-emocoes-monte-e-conte/monstro-das-emocoes-monte-e-conte.pdf', '/atividades/ludica/monstro-das-emocoes-monte-e-conte/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000028', 'Missão dos Piratas', 'Seis pistas indicam o caminho até o tesouro escondido. A criança recorta navio, caverna, vulcão, ponte e baú, monta o mapa na ordem certa e responde ao desafio extra.', 'ludica', 'pdf', '6-8', '40 min', 'ludica/missao-dos-piratas/missao-dos-piratas.pdf', '/atividades/ludica/missao-dos-piratas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000029', 'Parque dos Dinossauros', 'Nove dinossauros para recortar e colar no habitat correto — floresta, vulcão, lago, deserto ou caverna — com cards explicativos, três perguntas e o desafio de criar um dino inédito.', 'ludica', 'pdf', '6-8', '40 min', 'ludica/parque-dos-dinossauros/parque-dos-dinossauros.pdf', '/atividades/ludica/parque-dos-dinossauros/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000030', 'Laboratório do Cientista', 'Combina tubos de ensaio, ingredientes e equipamentos recortáveis em três experimentos, preenche a ficha da invenção e desenha o resultado. Inclui cartas-surpresa que mudam tudo.', 'ludica', 'pdf', '9-11', '40 min', 'ludica/laboratorio-do-cientista/laboratorio-do-cientista.pdf', '/atividades/ludica/laboratorio-do-cientista/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000031', 'Fábrica de Super-Heróis', 'Monta o herói com máscara, capa, uniforme, acessórios e símbolo recortáveis, escolhe os superpoderes, preenche a ficha e escreve uma aventura cumprindo as missões do dia.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/fabrica-de-super-herois/fabrica-de-super-herois.pdf', '/atividades/ludica/fabrica-de-super-herois/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000032', 'Construa um Castelo', 'Torres, muralhas, portões, bandeiras, decorações e personagens para recortar e montar o castelo. Depois a criança descreve quem mora nele, desenha o interior e cria o brasão.', 'producao-texto', 'pdf', '6-8', '40 min', 'ludica/construa-um-castelo/construa-um-castelo.pdf', '/atividades/ludica/construa-um-castelo/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000033', 'Safari dos Animais', 'Dez animais para recortar e colar no habitat certo — savana, floresta, oceano, deserto e polo norte —, três perguntas de observação, jogo da memória e um animal inventado.', 'ludica', 'pdf', '6-8', '40 min', 'ludica/safari-dos-animais/safari-dos-animais.pdf', '/atividades/ludica/safari-dos-animais/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000034', 'Mercado Divertido', 'Monta a cesta seguindo três listas de compras, recorta produtos por setor — hortifruti, laticínios, padaria, higiene e bebidas — e trabalha etiquetas de preço com cartas-surpresa.', 'ludica', 'pdf', '6-8', '40 min', 'ludica/mercado-divertido/mercado-divertido.pdf', '/atividades/ludica/mercado-divertido/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000035', 'Restaurante Maluco', 'Três clientes fazem pedidos e a criança monta cada prato com ingredientes recortáveis, escreve o menu do dia e encara o desafio do chef com as cartas-surpresa.', 'ludica', 'pdf', '6-8', '40 min', 'ludica/restaurante-maluco/restaurante-maluco.pdf', '/atividades/ludica/restaurante-maluco/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000036', 'Missão dos Bombeiros', 'Monta a cena de resgate com veículos, equipamentos e personagens recortáveis, numera o plano de resgate na ordem correta e escreve o que aconteceu. Ensina quando ligar 193.', 'ludica', 'pdf', '6-8', '40 min', 'ludica/missao-dos-bombeiros/missao-dos-bombeiros.pdf', '/atividades/ludica/missao-dos-bombeiros/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000037', 'Escola de Magia', 'Cria o próprio mago escolhendo chapéu, varinha, livro e cristal, inventa três poções e um feitiço, joga a memória mágica e escreve a aventura na escola de magia.', 'producao-texto', 'pdf', '6-8', '40 min', 'ludica/escola-de-magia/escola-de-magia.pdf', '/atividades/ludica/escola-de-magia/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000038', 'Navio Fantasma', 'Mistério de detetive a bordo: monta a cena com as peças recortáveis, resolve o enigma do código e preenche o diário do pirata contando o que descobriu.', 'ludica', 'pdf', '9-11', '40 min', 'ludica/navio-fantasma/navio-fantasma.pdf', '/atividades/ludica/navio-fantasma/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000039', 'Acampamento na Floresta', 'Monta o acampamento, escolhe seis itens essenciais para a mochila do explorador e registra a aventura no diário. Inclui cartas-surpresa e jogo da memória.', 'ludica', 'pdf', '6-8', '40 min', 'ludica/acampamento-na-floresta/acampamento-na-floresta.pdf', '/atividades/ludica/acampamento-na-floresta/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000040', 'Resgate no Fundo do Mar', 'Monta o cenário marinho, separa o que protege do que polui o mar, numera o plano de resgate e resolve o enigma do tesouro. Trabalha consciência ambiental.', 'ludica', 'pdf', '6-8', '40 min', 'ludica/resgate-no-fundo-do-mar/resgate-no-fundo-do-mar.pdf', '/atividades/ludica/resgate-no-fundo-do-mar/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000041', 'Óculos do Detetive', 'Recorta os óculos de lentes vermelha e azul, levanta três abas de pistas em camadas e descobre quem pegou o livro mágico da biblioteca. Trabalha inferência e dedução.', 'interpretacao-texto', 'pdf', '9-11', '30 min', 'ludica/oculos-do-detetive/oculos-do-detetive.pdf', '/atividades/ludica/oculos-do-detetive/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000042', 'Máquina das Escolhas', 'Três roletas presas com clipe sorteiam personagem, lugar e missão. A criança gira, combina os elementos e escreve a aventura que saiu no sorteio.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/maquina-das-escolhas/maquina-das-escolhas.pdf', '/atividades/ludica/maquina-das-escolhas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000043', 'Cidade Pop-Up', 'Seis prédios dobráveis, personagens e veículos para recortar e montar uma cidade em três dimensões sobre a base. Depois a criança cria histórias que acontecem nela.', 'ludica', 'pdf', '6-8', '40 min', 'ludica/cidade-pop-up/cidade-pop-up.pdf', '/atividades/ludica/cidade-pop-up/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000044', 'Trilha da Ilha do Tesouro', 'Jogo de tabuleiro completo para montar: dado de dobrar, marcadores em base de barco, cartas de aventura e envelope do tesouro. Trabalha leitura de instruções e jogo em grupo.', 'ludica', 'pdf', '6-8', '40 min', 'ludica/trilha-da-ilha-do-tesouro/trilha-da-ilha-do-tesouro.pdf', '/atividades/ludica/trilha-da-ilha-do-tesouro/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000045', 'Hospital das Frases', 'Cinco frases doentes para diagnosticar: falta de maiúscula, acentuação, pontuação e concordância. A criança encontra o erro e cola a correção recortada.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/hospital-das-frases/hospital-das-frases.pdf', '/atividades/ludica/hospital-das-frases/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000046', 'Guarda-Roupa das Palavras', 'Vinte palavras para recortar e guardar na gaveta certa: substantivo, verbo, adjetivo ou pronome. Fecha com a escrita de quatro frases usando as classes trabalhadas.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/guarda-roupa-das-palavras/guarda-roupa-das-palavras.pdf', '/atividades/ludica/guarda-roupa-das-palavras/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000047', 'Semáforo da Pontuação', 'Cola o sinal certo em cinco frases e depois reescreve duas delas trocando a pontuação para ver como o sentido muda. Trabalha ponto, vírgula, interrogação e exclamação.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/semaforo-da-pontuacao/semaforo-da-pontuacao.pdf', '/atividades/ludica/semaforo-da-pontuacao/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000048', 'História por Imagens', 'Quatro cenas para recortar e ordenar em começo, meio e fim. Com a sequência montada, a criança escreve a narrativa completa em quatro parágrafos.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/historia-por-imagens/historia-por-imagens.pdf', '/atividades/ludica/historia-por-imagens/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000049', 'Diário de um Personagem', 'Escolhe um entre quatro personagens, cola a figura e escreve uma página de diário em primeira pessoa. Inclui autoavaliação da produção escrita.', 'producao-texto', 'pdf', '9-11', '30 min', 'ludica/diario-de-um-personagem/diario-de-um-personagem.pdf', '/atividades/ludica/diario-de-um-personagem/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000050', 'Correio das Frases', 'Oito frases para recortar e entregar no envelope certo: pergunta, ordem, exclamação ou afirmação. Depois a criança escreve uma frase de cada tipo.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/correio-das-frases/correio-das-frases.pdf', '/atividades/ludica/correio-das-frases/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000051', 'Fábrica de Personagens', 'Escolhe aparência, personalidade, sonho, medo e objetivo, monta a ficha do personagem e escreve um texto apresentando-o. Base para qualquer produção narrativa.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/fabrica-de-personagens/fabrica-de-personagens.pdf', '/atividades/ludica/fabrica-de-personagens/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000052', 'Quebra-Cabeça dos Parágrafos', 'Cinco parágrafos embaralhados para recortar e colar na ordem que forma o texto. A criança cria um título e responde sobre a lição que a história deixa.', 'interpretacao-texto', 'pdf', '9-11', '30 min', 'ludica/quebra-cabeca-dos-paragrafos/quebra-cabeca-dos-paragrafos.pdf', '/atividades/ludica/quebra-cabeca-dos-paragrafos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000053', 'Máquina do Antes e Depois', 'Dez frases ilustradas para recortar e colar na coluna do passado, do presente ou do futuro. Fecha reescrevendo duas delas nos três tempos verbais.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/maquina-do-antes-e-depois/maquina-do-antes-e-depois.pdf', '/atividades/ludica/maquina-do-antes-e-depois/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000054', 'Cartas das Emoções', 'Combina personagem, situação e emoção e escreve o que aconteceu, como se sentiu, por quê e o que ajudaria. Trabalha vocabulário emocional e produção escrita.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/cartas-das-emocoes/cartas-das-emocoes.pdf', '/atividades/ludica/cartas-das-emocoes/capa.webp', 'Aulateca')
on conflict (id) do nothing;
