-- ════════════════════════════════════════════════════════════════════════════
-- 019 — Segunda leva do acervo: as fichas que o gestor entregou já em PDF.
--
-- GERADO por scripts/build-atividades.mjs a partir de
-- scripts/atividades.manifest.json. Não editar à mão: rode o script.
--
-- Por que não entrou na 012: a 012 já rodou em produção, e migration aplicada
-- não roda de novo. Acrescentar linhas lá deixaria o repositório dizendo uma
-- coisa e o banco outra. Num banco novo as duas rodam em ordem e o resultado
-- é o mesmo — a 019 é `on conflict do nothing` como a 012.
--
-- Mesmas regras da 012: file_url é caminho no bucket privado `atividades`,
-- image_url é a capa pública, uuids fixos para o seed ser idempotente.
-- ════════════════════════════════════════════════════════════════════════════

insert into public.resources
  (id, title, description, category, type, age_range, duration, file_url, image_url, author_name)
values
  ('a01a7eca-0002-4000-8000-000000000055', 'Detetive dos Erros', 'Cinco frases com erro de ortografia, pontuação ou concordância; a criança recorta a correção certa e cola ao lado. No desafio, reescreve uma delas trocando uma palavra por outra parecida.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/detetive-dos-erros/detetive-dos-erros.pdf', '/atividades/ludica/detetive-dos-erros/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000056', 'Jornal das Aventuras', 'Monta uma notícia colando manchete, personagem, local e acontecimento nos campos de quem, onde, quando e o quê, ilustra a matéria e cria uma manchete própria mais chamativa.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/jornal-das-aventuras/jornal-das-aventuras.pdf', '/atividades/ludica/jornal-das-aventuras/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000057', 'Mapa da História — Aventura na Floresta', 'Cola personagem, lugar, problema, acontecimento e final num mapa de trilha e depois reescreve a história completa com as próprias palavras, fechando com um título criativo.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/mapa-da-historia-aventura-na-floresta/mapa-da-historia-aventura-na-floresta.pdf', '/atividades/ludica/mapa-da-historia-aventura-na-floresta/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000058', 'Laboratório das Palavras — Misture as Sílabas', 'Combina sílabas de início, meio e fim para descobrir palavras reais e inventar palavras novas, separando as duas listas. No desafio, escreve uma frase com duas das palavras reais.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/laboratorio-das-palavras-misture-as-silabas/laboratorio-das-palavras-misture-as-silabas.pdf', '/atividades/ludica/laboratorio-das-palavras-misture-as-silabas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000059', 'Tribunal dos Personagens — O Vaso Quebrado', 'Diante de um menino que quebrou o vaso e inventou uma desculpa, a criança recorta argumentos a favor e contra, monta os dois lados e escreve sua conclusão e um conselho.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/tribunal-dos-personagens-o-vaso-quebrado/tribunal-dos-personagens-o-vaso-quebrado.pdf', '/atividades/ludica/tribunal-dos-personagens-o-vaso-quebrado/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000060', 'Varal das Frases — Sujeito, Verbo e Complemento', 'Recorta palavras soltas, monta três frases corretas no varal e depois separa cada uma em sujeito, verbo e complemento numa tabela. Fecha criando uma frase nova.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/varal-das-frases-sujeito-verbo-complemento/varal-das-frases-sujeito-verbo-complemento.pdf', '/atividades/ludica/varal-das-frases-sujeito-verbo-complemento/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000061', 'Restaurante dos Adjetivos', 'Escolhe entre dez adjetivos os que melhor descrevem cachorro, casa e menina e cola em cada prato. Depois escreve uma frase com um substantivo e dois adjetivos.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/restaurante-dos-adjetivos/restaurante-dos-adjetivos.pdf', '/atividades/ludica/restaurante-dos-adjetivos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000062', 'Elevador das Sílabas', 'Monta palavras com dezoito cartões de sílabas e leva cada uma ao andar certo do elevador: duas, três ou quatro sílabas. Registra uma palavra de cada andar.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/elevador-das-silabas/elevador-das-silabas.pdf', '/atividades/ludica/elevador-das-silabas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000063', 'Conserto de Histórias', 'Três historinhas têm um trecho que não faz sentido — peixe voando, casaco de lã na praia. A criança recorta a peça certa e troca, e depois inventa a própria correção.', 'interpretacao-texto', 'pdf', '6-8', '30 min', 'ludica/conserto-de-historias/conserto-de-historias.pdf', '/atividades/ludica/conserto-de-historias/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000064', 'Passaporte das Palavras', 'Doze palavras viajam para o país certo: substantivo, verbo, adjetivo, pronome ou advérbio. Depois a criança carimba o passaporte escrevendo uma frase que usa uma de cada.', 'ludica', 'pdf', '9-11', '40 min', 'ludica/passaporte-das-palavras/passaporte-das-palavras.pdf', '/atividades/ludica/passaporte-das-palavras/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000065', 'Quadrinhos Embaralhados', 'Quatro cenas de um menino que alimenta um cachorro de rua vêm fora de ordem: recorta, organiza, completa o último balão de fala e escreve o final da história.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/quadrinhos-embaralhados/quadrinhos-embaralhados.pdf', '/atividades/ludica/quadrinhos-embaralhados/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000066', 'Sorveteria das Rimas', 'Para cada casquinha — coração, bola, gato — escolhe as bolas de sorvete que rimam. Depois cria um versinho curto usando pelo menos uma das rimas.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/sorveteria-das-rimas/sorveteria-das-rimas.pdf', '/atividades/ludica/sorveteria-das-rimas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000067', 'Detetive do Sujeito — Cartões de Investigação', 'Quatro frases sem sujeito e quatro suspeitos para recortar e colar: quem latiu, quem estudou, quem decolou, quem explicou. Fecha inventando uma frase nova.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/detetive-do-sujeito-cartoes-de-investigacao/detetive-do-sujeito-cartoes-de-investigacao.pdf', '/atividades/ludica/detetive-do-sujeito-cartoes-de-investigacao/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000068', 'Correio do Futuro', 'Escolhe uma situação e um destinatário — você mesmo no futuro, um amigo, a família — e escreve uma carta completa, com começo, mensagem e despedida, num modelo de aerograma.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/correio-do-futuro/correio-do-futuro.pdf', '/atividades/ludica/correio-do-futuro/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000069', 'Semáforo da História', 'Organiza a história em começo, problema e final usando as três luzes do semáforo, escolhe cartões de personagem, lugar, problema e solução e escreve o texto completo ao lado.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/semaforo-da-historia/semaforo-da-historia.pdf', '/atividades/ludica/semaforo-da-historia/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000070', 'Caixa dos Começos', 'Escolhe um começo clássico — Era uma vez, De repente — e recorta cartas de personagem, lugar, objeto e problema para inspirar uma história inédita, com título e cena desenhada.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/caixa-dos-comecos/caixa-dos-comecos.pdf', '/atividades/ludica/caixa-dos-comecos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000071', 'Máquina do Singular e Plural', 'Cola seis palavras no singular na entrada da máquina e o plural correspondente na saída. Depois escreve uma frase com uma das palavras no plural.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/maquina-do-singular-e-plural/maquina-do-singular-e-plural.pdf', '/atividades/ludica/maquina-do-singular-e-plural/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000072', 'Detetive da Pontuação — Cinco Pistas', 'Cinco frases sem pontuação viram pistas: a criança recorta os sinais e descobre qual completa cada uma, com um quadro de dicas explicando o que cada sinal faz.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/detetive-da-pontuacao-cinco-pistas/detetive-da-pontuacao-cinco-pistas.pdf', '/atividades/ludica/detetive-da-pontuacao-cinco-pistas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000073', 'Mapa do Conto', 'Um mapa do tesouro organiza personagem, lugar, problema e solução com cartas para recortar — pirata, ilha misteriosa, dragão bravo — e a criança escreve o resumo do conto que montou.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/mapa-do-conto/mapa-do-conto.pdf', '/atividades/ludica/mapa-do-conto/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000074', 'Relógio dos Tempos Verbais', 'Nove frases recortadas vão para o setor certo do relógio: passado, presente ou futuro. Depois a criança escreve uma frase própria em cada tempo.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/relogio-dos-tempos-verbais/relogio-dos-tempos-verbais.pdf', '/atividades/ludica/relogio-dos-tempos-verbais/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000075', 'Oficina dos Quadrinhos', 'Monta uma tirinha de quatro quadros com personagens, cenários, balões, emoções e onomatopeias para recortar, dá um título e conta a mesma história em texto corrido.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/oficina-dos-quadrinhos/oficina-dos-quadrinhos.pdf', '/atividades/ludica/oficina-dos-quadrinhos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000076', 'Tribunal dos Personagens — O Livro Esquecido', 'Lucas esqueceu de devolver o livro da biblioteca. A criança cola argumentos de defesa e de acusação, escreve o veredito com sua opinião e desenha a cena da história.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/tribunal-dos-personagens-o-livro-esquecido/tribunal-dos-personagens-o-livro-esquecido.pdf', '/atividades/ludica/tribunal-dos-personagens-o-livro-esquecido/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000077', 'Laboratório dos Sinônimos', 'Cinco estações com feliz, rápido, bonito, grande e bravo esperam a palavra de significado parecido. A criança cola o sinônimo certo e escreve uma frase com um dos pares.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/laboratorio-dos-sinonimos/laboratorio-dos-sinonimos.pdf', '/atividades/ludica/laboratorio-dos-sinonimos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000078', 'Trem da Sequência', 'Quatro cenas mostram uma semente virando flor: recorta, coloca na ordem certa dentro dos vagões e conta a história com as próprias palavras, inventando um vagão a mais.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/trem-da-sequencia/trem-da-sequencia.pdf', '/atividades/ludica/trem-da-sequencia/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000079', 'Baú das Perguntas', 'Lê um texto curto sobre um passeio no parque e encaixa em cada baú a resposta de quem, onde, quando e o que levou. Fecha criando uma pergunta nova para o texto.', 'interpretacao-texto', 'pdf', '6-8', '30 min', 'ludica/bau-das-perguntas/bau-das-perguntas.pdf', '/atividades/ludica/bau-das-perguntas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000080', 'Jardim dos Substantivos', 'Planta oito palavras no canteiro certo — pessoas, animais, objetos ou lugares — e depois escreve uma frase com a palavra favorita e desenha um substantivo novo para cada grupo.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/jardim-dos-substantivos/jardim-dos-substantivos.pdf', '/atividades/ludica/jardim-dos-substantivos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000081', 'Missão dos Conectivos', 'Cinco pares de ideias precisam de uma ponte: mas, porque, e, então ou porém. A criança cola o conectivo que liga melhor cada frase e depois cria uma frase própria.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/missao-dos-conectivos/missao-dos-conectivos.pdf', '/atividades/ludica/missao-dos-conectivos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000082', 'Cinema da Redação', 'Escolhe personagem, lugar, problema e final entre dezesseis cartas, escreve o roteiro do filme e ainda cria o título e o cartaz de cinema da própria história.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/cinema-da-redacao/cinema-da-redacao.pdf', '/atividades/ludica/cinema-da-redacao/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000083', 'Radar dos Antônimos', 'Cinco radares mostram alto, quente, cheio, feliz e dia; a criança encontra e cola o contrário de cada um e escreve uma frase usando um dos pares opostos.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/radar-dos-antonimos/radar-dos-antonimos.pdf', '/atividades/ludica/radar-dos-antonimos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000084', 'Oficina das Manchetes', 'Três notícias ilustradas — o cachorro que salvou a bola, a horta da escola, a feira de ciências — e seis manchetes para escolher a que combina. Depois escreve como repórter por um dia.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/oficina-das-manchetes/oficina-das-manchetes.pdf', '/atividades/ludica/oficina-das-manchetes/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000085', 'Roda dos Pronomes', 'Quatro rodas — eu, você, ele/ela, nós — esperam o pronome certo para completar cada frase, com dois cartões intrusos que não são pronomes. Fecha com uma frase própria.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/roda-dos-pronomes/roda-dos-pronomes.pdf', '/atividades/ludica/roda-dos-pronomes/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000086', 'Mercado dos Verbos', 'Cinco bancas do mercado mostram alguém correndo, lendo, dormindo, escrevendo e cantando; a criança cola o verbo certo em cada uma e descarta os dois cartões que não são verbos.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/mercado-dos-verbos/mercado-dos-verbos.pdf', '/atividades/ludica/mercado-dos-verbos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000087', 'Detetive do Sujeito — Quem Praticou a Ação?', 'Seis frases sem sujeito e dez suspeitos para recortar: o menino, a professora, os amigos, o gato. No desafio, reescreve duas frases trocando o sujeito por outro que também faça sentido.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/detetive-do-sujeito-quem-praticou-a-acao/detetive-do-sujeito-quem-praticou-a-acao.pdf', '/atividades/ludica/detetive-do-sujeito-quem-praticou-a-acao/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000088', 'A História em Ordem', 'Quatro cenas da adoção de um cachorrinho num abrigo vêm embaralhadas: a criança organiza, escreve a história completa, cria um título e responde o que aprendeu com ela.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/a-historia-em-ordem/a-historia-em-ordem.pdf', '/atividades/ludica/a-historia-em-ordem/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000089', 'Caça-Palavras Temático — Natureza', 'Onze palavras da natureza escondidas na grade, mais perguntas sobre quantas foram achadas e qual é a maior e a menor. Fecha com um pequeno texto sobre a natureza.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/caca-palavras-tematico-natureza/caca-palavras-tematico-natureza.pdf', '/atividades/ludica/caca-palavras-tematico-natureza/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000090', 'Caça ao Tesouro das Palavras — A Aventura no Bosque', 'Lê o conto de Lucas no bosque, responde quatro perguntas de interpretação, garimpa substantivos, adjetivos e verbos no texto e escreve o que gostaria de achar numa caixa misteriosa.', 'interpretacao-texto', 'pdf', '9-11', '40 min', 'ludica/caca-ao-tesouro-das-palavras-a-aventura-no-bosque/caca-ao-tesouro-das-palavras-a-aventura-no-bosque.pdf', '/atividades/ludica/caca-ao-tesouro-das-palavras-a-aventura-no-bosque/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000091', 'Caça aos Sinônimos e Antônimos', 'Cinco palavras, duas colunas: a criança cola o sinônimo e o antônimo de cada uma e escreve frases mostrando que entendeu a diferença entre significado parecido e oposto.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/caca-aos-sinonimos-e-antonimos/caca-aos-sinonimos-e-antonimos.pdf', '/atividades/ludica/caca-aos-sinonimos-e-antonimos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000092', 'Missão Leitor Detetive', 'Sobre o texto O cachorro e a chuva: cinco perguntas de interpretação, verdadeiro ou falso, caça a palavras com significado dado, completar frases e uma produção de texto ao final.', 'interpretacao-texto', 'pdf', '9-11', '40 min', 'ludica/missao-leitor-detetive/missao-leitor-detetive.pdf', '/atividades/ludica/missao-leitor-detetive/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000093', 'Leitura em Ação — O Dia em Que Tudo Mudou', 'Lê a história do filhote que chegou numa caixa, responde seis perguntas incluindo a mensagem principal, ordena quatro cenas e escreve um novo final.', 'interpretacao-texto', 'pdf', '9-11', '40 min', 'ludica/leitura-em-acao-o-dia-em-que-tudo-mudou/leitura-em-acao-o-dia-em-que-tudo-mudou.pdf', '/atividades/ludica/leitura-em-acao-o-dia-em-que-tudo-mudou/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000094', 'Detetive das Palavras — Substantivos na Cena', 'Observa uma cena de quintal e classifica dez substantivos em pessoas, animais, lugares, objetos e sentimentos. Depois escreve três frases usando as palavras da cena.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/detetive-das-palavras-substantivos-na-cena/detetive-das-palavras-substantivos-na-cena.pdf', '/atividades/ludica/detetive-das-palavras-substantivos-na-cena/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000095', 'História em Construção — O Dia Especial', 'Um texto lacunado sobre um passeio de domingo, com banco de nove palavras para recortar e colar. Depois a criança dá outro título, desenha e reescreve a história completa.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/historia-em-construcao-o-dia-especial/historia-em-construcao-o-dia-especial.pdf', '/atividades/ludica/historia-em-construcao-o-dia-especial/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000096', 'Laboratório das Palavras — Oficina Completa', 'Seis desafios numa folha só: classificar palavras em quatro classes, formar palavras com sílabas, completar frases, reorganizar frases embaralhadas, criar frases a partir de imagens e montar frases com cartões.', 'ludica', 'pdf', '9-11', '40 min', 'ludica/laboratorio-das-palavras-oficina-completa/laboratorio-das-palavras-oficina-completa.pdf', '/atividades/ludica/laboratorio-das-palavras-oficina-completa/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000097', 'Jornal Maluco', 'Monta a capa de um jornal escolhendo manchete, imagem e fonte entre as opções recortáveis, e depois escreve a própria notícia respondendo o quê, quem, quando, onde e por quê.', 'producao-texto', 'pdf', '9-11', '40 min', 'ludica/jornal-maluco/jornal-maluco.pdf', '/atividades/ludica/jornal-maluco/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000098', 'Casas das Palavras — Sinônimos e Antônimos', 'Vinte palavras se mudam para a casa certa: a dos sinônimos ou a dos antônimos. Depois a criança escolhe dois pares e forma frases no caderno.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/casas-das-palavras-sinonimos-e-antonimos/casas-das-palavras-sinonimos-e-antonimos.pdf', '/atividades/ludica/casas-das-palavras-sinonimos-e-antonimos/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000099', 'Caça ao Texto', 'Cinco trechos de uma história sobre o cachorro Max vêm embaralhados: a criança organiza na ordem certa, responde quatro perguntas sobre o texto montado e cria um final diferente.', 'interpretacao-texto', 'pdf', '6-8', '30 min', 'ludica/caca-ao-texto/caca-ao-texto.pdf', '/atividades/ludica/caca-ao-texto/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000100', 'Missão: Classificar Palavras', 'Vinte palavras para recortar e distribuir entre substantivos, verbos e adjetivos, com a dica de que a mesma palavra muda de classe conforme o contexto.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/missao-classificar-palavras/missao-classificar-palavras.pdf', '/atividades/ludica/missao-classificar-palavras/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000101', 'Varal das Frases — Palavras e Figuras', 'Cinco figuras — cachorro, menino, menina, carro, sol — pedem a frase certa, montada com palavras e imagens recortadas. Depois cria outra frase com as mesmas palavras.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/varal-das-frases-palavras-e-figuras/varal-das-frases-palavras-e-figuras.pdf', '/atividades/ludica/varal-das-frases-palavras-e-figuras/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000102', 'A Ordem das Palavras', 'Quatro frases embaralhadas para recortar, ordenar e reescrever, com a lembrança de que frase começa com maiúscula e termina com ponto. Fecha com um desenho de uma delas.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/a-ordem-das-palavras/a-ordem-das-palavras.pdf', '/atividades/ludica/a-ordem-das-palavras/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000103', 'Varal das Frases — Leia em Voz Alta', 'Três frases para montar no varal com palavras recortadas e ler em voz alta. No desafio, circula o sujeito e sublinha o verbo de cada frase formada.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/varal-das-frases-leia-em-voz-alta/varal-das-frases-leia-em-voz-alta.pdf', '/atividades/ludica/varal-das-frases-leia-em-voz-alta/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000104', 'Monte a História', 'Recorta três cenas e quatro frases da aventura de Pedro na chuva, organiza em começo, meio e fim, dá um título e reescreve a história completa em voz alta.', 'producao-texto', 'pdf', '6-8', '30 min', 'ludica/monte-a-historia/monte-a-historia.pdf', '/atividades/ludica/monte-a-historia/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000105', 'Palavras com Mais de Um Sentido', 'Seis frases e seis homônimas — pão, pneu, pássaro, copo, anzol, comer — para colar no lugar certo, mostrando que o sentido depende do contexto.', 'ludica', 'pdf', '9-11', '20 min', 'ludica/palavras-com-mais-de-um-sentido/palavras-com-mais-de-um-sentido.pdf', '/atividades/ludica/palavras-com-mais-de-um-sentido/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000106', 'Varal das Frases — Fique Atento', 'Monta três frases no varal e confere numa lista de verificação se cada uma começa com maiúscula, tem sentido e termina com ponto final.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/varal-das-frases-fique-atento/varal-das-frases-fique-atento.pdf', '/atividades/ludica/varal-das-frases-fique-atento/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000107', 'Onde Cabe? — Substantivos em Ação', 'Oito figuras e quinze palavras para separar em pessoas, animais, lugares e objetos. Depois a criança escolhe duas de cada grupo e cria uma frase para cada.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/onde-cabe-substantivos-em-acao/onde-cabe-substantivos-em-acao.pdf', '/atividades/ludica/onde-cabe-substantivos-em-acao/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000108', 'Qual é a Classe?', 'Vinte e cinco palavras ilustradas para distribuir entre substantivo, verbo, adjetivo, pronome e advérbio, com a definição de cada classe no topo da coluna.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/qual-e-a-classe/qual-e-a-classe.pdf', '/atividades/ludica/qual-e-a-classe/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000109', 'Classifique as Palavras — Quatro Classes', 'Vinte palavras para recortar e colar em substantivo, verbo, adjetivo ou advérbio. No desafio, escolhe três de cada categoria e cria uma frase criativa.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/classifique-as-palavras-quatro-classes/classifique-as-palavras-quatro-classes.pdf', '/atividades/ludica/classifique-as-palavras-quatro-classes/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000110', 'Sílabas em Ação', 'Trinta cartões de sílabas para juntar e formar palavras de animais, objetos, alimentos e lugares, colando cada uma no quadro certo e lendo em voz alta.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/silabas-em-acao/silabas-em-acao.pdf', '/atividades/ludica/silabas-em-acao/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000111', 'Palavras em Ordem', 'Cinco frases ilustradas para montar com palavras recortadas na ordem certa. Depois a criança escolhe uma e escreve outra bem parecida.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/palavras-em-ordem/palavras-em-ordem.pdf', '/atividades/ludica/palavras-em-ordem/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000112', 'Sons que Combinam', 'Oito figuras — bola, gato, sol, flor, pato, cão, casa, praia — e dezoito palavras para colar as que rimam com cada uma. Trabalha consciência fonológica.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/sons-que-combinam/sons-que-combinam.pdf', '/atividades/ludica/sons-que-combinam/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000113', 'Classifique as Palavras — Cinco Colunas', 'Vinte palavras para separar em substantivos, verbos, adjetivos, pronomes e advérbios, com a definição de cada classe. Fecha escolhendo três colunas e criando uma frase.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/classifique-as-palavras-cinco-colunas/classifique-as-palavras-cinco-colunas.pdf', '/atividades/ludica/classifique-as-palavras-cinco-colunas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000114', 'Sinônimos e Antônimos — Recorte e Cole', 'Oito palavras numa tabela de três colunas: a criança cola o sinônimo e o antônimo de cada uma entre dezesseis cartões e depois forma frases com duas delas.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/sinonimos-e-antonimos-recorte-e-cole/sinonimos-e-antonimos-recorte-e-cole.pdf', '/atividades/ludica/sinonimos-e-antonimos-recorte-e-cole/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000115', 'Ligue e Complete — Quem Faz o Quê?', 'Combina seis substantivos com seis verbos e completa cada frase com o complemento certo — parque, livro, maçã, galho, cama, bola — lendo tudo em voz alta.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/ligue-e-complete-quem-faz-o-que/ligue-e-complete-quem-faz-o-que.pdf', '/atividades/ludica/ligue-e-complete-quem-faz-o-que/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000116', 'Classifique as Palavras — Vinte Cartões', 'Vinte cartões para colar em cinco colunas de classes gramaticais, com cinco espaços por coluna. No desafio, cria frases com duas palavras de cada uma.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/classifique-as-palavras-vinte-cartoes/classifique-as-palavras-vinte-cartoes.pdf', '/atividades/ludica/classifique-as-palavras-vinte-cartoes/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000117', 'Caça ao Sinônimo', 'Oito palavras ilustradas — feliz, casa, carro, presente, rápido, triste, amor, cachorro — e oito sinônimos para encontrar e colar. Fecha com duas frases usando os sinônimos.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/caca-ao-sinonimo/caca-ao-sinonimo.pdf', '/atividades/ludica/caca-ao-sinonimo/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000118', 'Classifique as Palavras — Com Interjeições', 'Seis classes, interjeições incluídas, e vinte e quatro palavras para distribuir entre elas. Depois a criança escolhe três e cria uma frase para cada.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/classifique-as-palavras-com-interjeicoes/classifique-as-palavras-com-interjeicoes.pdf', '/atividades/ludica/classifique-as-palavras-com-interjeicoes/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000119', 'Complete o Texto — Meu Dia na Escola', 'Texto lacunado com cinco palavras dadas — escola, amigos, brincar, aprender, feliz — e um espaço grande para desenhar sobre o que foi lido.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/complete-o-texto-meu-dia-na-escola/complete-o-texto-meu-dia-na-escola.pdf', '/atividades/ludica/complete-o-texto-meu-dia-na-escola/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000120', 'Caça-Palavras Temático — Escola e Amizade', 'Dez palavras sobre escola, estudo e convivência escondidas na horizontal, na vertical e na diagonal, numa grade de doze colunas.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/caca-palavras-tematico-escola-e-amizade/caca-palavras-tematico-escola-e-amizade.pdf', '/atividades/ludica/caca-palavras-tematico-escola-e-amizade/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000121', 'Complete com as Palavras Adequadas', 'Dez frases ilustradas para completar com as palavras do quadro, cada uma apoiada num desenho que ajuda a criança a escolher certo.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/complete-com-as-palavras-adequadas/complete-com-as-palavras-adequadas.pdf', '/atividades/ludica/complete-com-as-palavras-adequadas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000122', 'Oficina de Língua Portuguesa — Nove Desafios', 'Uma folha com nove seções: caça-palavras, completar frases, separar sílabas, formar frases a partir de imagem, achar o intruso, ordenar palavras, ligar sinônimos, escrever antônimos e completar um texto.', 'ludica', 'pdf', '9-11', '40 min', 'ludica/oficina-de-lingua-portuguesa-nove-desafios/oficina-de-lingua-portuguesa-nove-desafios.pdf', '/atividades/ludica/oficina-de-lingua-portuguesa-nove-desafios/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000123', 'Caça-Palavras Temático — Forme Frases', 'Dez palavras sobre escola e futuro na grade; depois a criança escolhe três para escrever frases e uma para desenhar e descrever.', 'ludica', 'pdf', '6-8', '30 min', 'ludica/caca-palavras-tematico-forme-frases/caca-palavras-tematico-forme-frases.pdf', '/atividades/ludica/caca-palavras-tematico-forme-frases/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000124', 'Complete com as Palavras — Dez Frases', 'Dez frases sobre o dia a dia para completar com as palavras do quadro. No desafio, reescreve três delas com outras palavras mantendo o mesmo sentido.', 'ludica', 'pdf', '6-8', '20 min', 'ludica/complete-com-as-palavras-dez-frases/complete-com-as-palavras-dez-frases.pdf', '/atividades/ludica/complete-com-as-palavras-dez-frases/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000125', 'Leitura e Interpretação — O Cachorro e o Balão', 'Lê a história da cachorrinha Luna e do balão preso na árvore e responde oito perguntas, da mais direta à de opinião, fechando com um desafio de imaginação.', 'interpretacao-texto', 'pdf', '6-8', '30 min', 'ludica/leitura-e-interpretacao-o-cachorro-e-o-balao/leitura-e-interpretacao-o-cachorro-e-o-balao.pdf', '/atividades/ludica/leitura-e-interpretacao-o-cachorro-e-o-balao/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000126', 'Leitura com Atenção — O Livro Mágico', 'Sobre o conto do livro que transporta Lívia para outro mundo: oito questões que misturam pergunta aberta, múltipla escolha, marcação de características e opinião.', 'interpretacao-texto', 'pdf', '9-11', '30 min', 'ludica/leitura-com-atencao-o-livro-magico/leitura-com-atencao-o-livro-magico.pdf', '/atividades/ludica/leitura-com-atencao-o-livro-magico/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000127', 'Caça-Palavras Temático — Palavras e Conquistas', 'Oito palavras sobre escola, família e sonhos na grade; depois a criança escreve três frases e responde qual palavra mais combina com ela e por quê.', 'ludica', 'pdf', '9-11', '30 min', 'ludica/caca-palavras-tematico-palavras-e-conquistas/caca-palavras-tematico-palavras-e-conquistas.pdf', '/atividades/ludica/caca-palavras-tematico-palavras-e-conquistas/capa.webp', 'Aulateca'),
  ('a01a7eca-0002-4000-8000-000000000128', 'Caça-Palavras dos Animais', 'Dez animais escondidos na grade, mais três seções de ortografia e escrita: completar com S, SS, C ou Ç, separar sílabas e formar frases criativas.', 'ludica', 'pdf', '9-11', '40 min', 'ludica/caca-palavras-dos-animais/caca-palavras-dos-animais.pdf', '/atividades/ludica/caca-palavras-dos-animais/capa.webp', 'Aulateca')
on conflict (id) do nothing;
